force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Callout_URL__c.field-meta.xml
<CustomField>
    <fullName>Callout_URL__c</fullName>
    <label>Callout URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Custom_Apex_Handler__c.field-meta.xml
<CustomField>
    <fullName>Custom_Apex_Handler__c</fullName>
    <label>Custom Apex Handler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/External_Id_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Id_Field_API_Name__c</fullName>
    <description>This field is populated from webservice for Inbound only</description>
    <label>External Id Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Flat_Key_for_Resource__c.field-meta.xml
<CustomField>
    <fullName>Flat_Key_for_Resource__c</fullName>
    <description>Defines the flat key in incoming JSON that will be used to identify the Resource and hence the object setting</description>
    <label>Flat Key for Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Force_Sync__c.field-meta.xml
<CustomField>
    <fullName>Force_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Force Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/How_to_process__c.field-meta.xml
<CustomField>
    <fullName>How_to_process__c</fullName>
    <label>How to process?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>use_object_setting</fullName>
                <default>true</default>
                <label>Use Object Setting</label>
            </value>
            <value>
                <fullName>use_custom_apex_handler</fullName>
                <label>Use Custom Apex Handler</label>
            </value>
            <value>
                <fullName>ignore_log</fullName>
                <label>Ignore Log</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Integration_Setting__c.field-meta.xml
<CustomField>
    <fullName>Integration_Setting__c</fullName>
    <label>Integration Setting</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Is_Notification_Only__c.field-meta.xml
<CustomField>
    <fullName>Is_Notification_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Notification Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/ObjectSettingId__c.field-meta.xml
<CustomField>
    <fullName>ObjectSettingId__c</fullName>
    <label>Object Setting</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>SYS_IntegrationLog__c</referenceTo>
    <relationshipLabel>SYS_IntegrationLogs</relationshipLabel>
    <relationshipName>SYS_IntegrationLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Request_Digest__c.field-meta.xml
<CustomField>
    <fullName>Request_Digest__c</fullName>
    <label>Request Digest</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Requires_process_on_complete__c.field-meta.xml
<CustomField>
    <fullName>Requires_process_on_complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires process on complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/retry__c.field-meta.xml
<CustomField>
    <fullName>retry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;NEW&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>CALLOUT ERROR</label>
            </value>
            <value>
                <fullName>PENDING_PARENT</fullName>
                <label>PENDING PARENT</label>
            </value>
            <value>
                <fullName>READY_FOR_PROCESSING</fullName>
                <label>READY FOR PROCESSING</label>
            </value>
            <value>
                <fullName>ENQUEUED_FOR_RETRY</fullName>
                <label>ENQUEUED FOR RETRY</label>
            </value>
            <value>
                <fullName>READY_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>READY_FOR_PARENT</label>
            </value>
            <value>
                <fullName>WAITING_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>WAITING_FOR_PARENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_Http_Status__c.field-meta.xml
<CustomField>
    <fullName>SYS_Http_Status__c</fullName>
    <label>Http Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>SYS_Operation_Type__c</fullName>
    <label>Operation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MERGE</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>UPSERT</fullName>
            </value>
            <value>
                <fullName>INSERT</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
            <value>
                <fullName>CDC</fullName>
                <isActive>false</isActive>
                <label>CDC</label>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
                <isActive>false</isActive>
                <label>RESPONSE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_RequestId__c.field-meta.xml
<CustomField>
    <fullName>SYS_RequestId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RequestId</label>
    <referenceTo>SYS_IntegrationLog__c</referenceTo>
    <relationshipLabel>Callout Response Logs</relationshipLabel>
    <relationshipName>RequestId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SYS_IntegrationUtility.cls
public inherited sharing class SYS_IntegrationUtility extends SYS_ApplicationService{
    // public SYS_IntegrationUtility() {

    // }

    // public class SYS_IntegrationUtilityException extends Exception{}

    // public void processInboundRecord(SYS_IntegrationLog__c log) {
    //     Map<SYS_IntegrationLog__c, sObject> mapLogrecVsObject
    // }

    // public void doDMLNew(Map<SYS_IntegrationLog__c, sObject> records,String dmlType,String additionalSetting, Map<String, SYS_IntegrationLog__c> sysLogMap ) {
        
        
    //     switch on dmlType.toUpperCase() {
    //         when 'INSERT'{
    //             doInsertNew(records, sysLogMap);
    //         }
    //         when 'UPSERT'{
    //             doUpsertNew(records, additionalSetting, sysLogMap);
    //         }
    //         when 'UPDATE'{
    //             doUpdateNew(records, sysLogMap);
    //         }
    //         when 'DELETE'{
    //             doDeleteNew(records, sysLogMap);
    //         }
    //         when else {
    //             SYS_debug.log('Invalid DML Operation specified in log record:'+dmlType);
    //             return ;
    //         }
            
    //     }

    // }

    // public void doInsertNew(Map<SYS_IntegrationLog__c, sObject> records, Map<String, SYS_IntegrationLog__c> sysLogMap){
    //     Database.SaveResult[] results;
    //     Boolean success = true;
    //     results = Database.insert(records?.values(), false);

    //     for(integer i=0; i < records?.values()?.size() ; i++) {
    //         String syslogId = (String)records?.values()[i]?.get('Last_Processed_SYSLog__c');
    //         generatelogForInboundResult(results[i].isSuccess(), sysLogMap.get(syslogId));

    //         if( !results[i].isSuccess() ) { // Update the error in sysLog
    //             SYS_Helper.handleFailureDml(sysLogMap.get(syslogId), results[i]?.getErrors());
    //         } else {
                
    //             SYS_Helper.handleSuccessDml(sysLogMap.get(syslogId), results[i]?.getId());
    //         }
    //     }
    //     // if(!results[0].isSuccess()){
    //     //     success = false;
    //     //     handleDMLErrors(results[0].getErrors(),log);
    //     // }
    //     // else{
    //     //     log.WhatId__c = results[0].getId();
    //     // }

    //     return ;
    // }

    // public void doUpdateNew(Map<SYS_IntegrationLog__c, sObject> records, Map<String, SYS_IntegrationLog__c> sysLogMap){
    //     Database.SaveResult[] results;
    //     Boolean success = true;
    //     results = Database.update(records?.values(), false);

    //     for(integer i=0; i < records?.values()?.size() ; i++) {
    //         String syslogId = (String)records?.values()[i]?.get('Last_Processed_SYSLog__c');
    //         generatelogForInboundResult(results[i].isSuccess(), sysLogMap.get(syslogId));
            
    //         if( !results[i].isSuccess() ) { // Update the error in sysLog
    //             SYS_Helper.handleFailureDml(sysLogMap.get(syslogId), results[i]?.getErrors());
    //         } else {
    //             SYS_Helper.handleSuccessDml(sysLogMap.get(syslogId), results[i]?.getId());
    //         }
    //     }
    //     // if(!results[0].isSuccess()){
    //     //     success = false;
    //     //     handleDMLErrors(results[0].getErrors(),log);
    //     // }
    //     // else{
    //     //     log.WhatId__c = results[0].getId();
    //     // }

    //     return ;
    // }

    // public void doDeleteNew(Map<SYS_IntegrationLog__c, sObject> records, Map<String, SYS_IntegrationLog__c> sysLogMap){
    //     Database.DeleteResult[] results;
    //     Boolean success = true;
    //     results = SYS_Helper.deleteWithFLSCheck(records?.values());


    //     for(integer i=0; i < records?.values()?.size() ; i++) {
    //         String syslogId = (String)records?.values()[i]?.get('Last_Processed_SYSLog__c');
    //         generatelogForInboundResult(results[i].isSuccess(), sysLogMap.get(syslogId));
            
    //         if( !results[i].isSuccess() ) { // Update the error in sysLog
    //             SYS_Helper.handleFailureDml(sysLogMap.get(syslogId), results[i]?.getErrors());
    //         } else {
                
    //             SYS_Helper.handleSuccessDml(sysLogMap.get(syslogId), results[i]?.getId());
    //         }
    //     }

    //     // if(!results[0].isSuccess()){
    //     //     success = false;
    //     //     handleDMLErrors(results[0].getErrors(),log);
    //     // }
    //     // else{
    //     //     log.WhatId__c = results[0].getId();
    //     // }

    //     return ;
    // }

    // public void doUpsertNew(Map<SYS_IntegrationLog__c, sObject> records,String additionalSetting,Map<String, SYS_IntegrationLog__c> sysLogMap){
    //     Database.UpsertResult[] results;
    //     Boolean success = true;
    //     if(String.isBlank(additionalSetting))
    //         results = Database.upsert(records?.values(), false);
    //     else{
    //         /*--*/SYS_debug.log('--MS externalIdField for:'+records?.values()[0]+' : '+additionalSetting);
    //         //Schema.SObjectField externalIdField = Schema.getGlobalDescribe().get(SYS_DataCache.sObjectApiName).getDescribe().fields.getMap().get(additionalSetting); 
            
    //         Schema.SObjectField externalIdField = records?.values()[0].getSObjectType().getDescribe().fields.getMap().get(additionalSetting); 
    //         /*--*/SYS_debug.log('--MS externalIdField in doUpsert:'+externalIdField);
            
    //         results = Database.upsert(records?.values(), externalIdField, false);
    //     }

    //     for(integer i=0; i < records?.values()?.size() ; i++) {
    //         String syslogId = (String)records?.values()[i]?.get('Last_Processed_SYSLog__c');
    //         generatelogForInboundResult(results[i].isSuccess(), sysLogMap.get(syslogId));
            
    //         System.debug('record ifsuccess '+records?.values()[i]?.Id);
    //         if(!results[i].isSuccess()) { // Update the error in sysLog
    //             SYS_Helper.handleFailureDml(sysLogMap.get(syslogId), results[i]?.getErrors());
    //         } else {
                
    //             SYS_Helper.handleSuccessDml(sysLogMap.get(syslogId), results[i]?.getId());
    //         }
    //     }
        
    //     // /*--*/SYS_debug.log('--MS Log check # '+log.Id+' has WhatId: '+results[0].getId());

    //     // if(!results[0].isSuccess()){
    //     //     success = false;
    //     //     handleDMLErrors(results[0].getErrors(),log);
    //     // }
    //     // else{
    //     //     log.WhatId__c = results[0].getId();
    //     // }
    //     // /*--*/SYS_debug.log('--MS Log re-check # '+log.Id+' has WhatId: '+log.WhatId__c);

    //     return ;
    // }


    //NO OVERRIDES----######
    // public override SYS_IntegrationLog__c generatelogForInboundResult(Boolean result,SYS_IntegrationLog__c log){

    //     SYS_IntegrationLog__c logResp = new SYS_IntegrationLog__c();
        
    //     /*--*/SYS_debug.log('Beginning. Log status for:'+logResp.Request_Digest__c+'='+logResp.Status__c);


    //     if(!result){
            
    //         //-- Error message is set in handleDmlErrors
    //         //String errorMessage = 'Error while processing inbound';

    //         logResp.Status__c = 'FAIL';
    //         logResp.retry__c = true;
    //         //## SYS_Helper.flagLogForRetry(logResp.Id);
            

    //         /*
    //         if (Schema.sObjectType.SYS_IntegrationLog__c.fields.Message__c.isCreateable()) {
    //             logResp.Message__c = errorMessage;
    //         }
    //         */
            
    //         logResp.Id = log.Id;
            
    //     }
    //     else{
            
    //         //ID jobID = System.enqueueJob(new SYS_ParentChildRecordsQueueable(log,SYS_DataCache.INT_TYPE));
    //         logResp = log;
    //         logResp.ObjectSettingId__c = SYS_DataCache.OBJ_TYPE;

    //         //logResp.Status__c = 'DONE';

    //         /**
    //          * Check if there are other siblings. Call parenting queueable only if all are done
    //          */

    //         /*--*/SYS_debug.log('MS totalChildRecords B4:'+SYS_QueueableForInboundChild.totalChildRecords);
    //         SYS_QueueableForInboundChild.totalChildRecords--;
    //         /*--*/SYS_debug.log('MS totalChildRecords After:'+SYS_QueueableForInboundChild.totalChildRecords);
           
    //         /*--*/SYS_debug.log('MS Condition chck for Parenting:'+log.Requires_process_on_complete__c);
    //         /*--*/SYS_debug.log('MS Condition chck for Parenting:'+(SYS_QueueableForInboundChild.totalChildRecords==0));
    //         /*--*/SYS_debug.log('MS Condition chck for Parenting:'+log.Status__c);


    //         /**
    //          * If the log is for either a parent or the LAST sibling of n children or a child
    //          * being processed as part of retry. Therefore in  else we again need to make checks for parent vs. child
    //          * and set the Status accordingly.
    //          */
    //         if(log.Requires_process_on_complete__c 
    //             && (SYS_QueueableForInboundChild.totalChildRecords==0 || log.Status__c==SYS_Constants.READY_FOR_PROCESSING))
    //         {
    //             /*--*/SYS_debug.log('MS Queueable Jobs in queue:'+Limits.getQueueableJobs());
    //             /*--*/SYS_debug.log('MS Queueable Allowed:'+Limits.getLimitQueueableJobs());

    //             logResp.Status__c = 'PENDING_PARENT';
    //             logResp.retry__c = true;
    //             //## SYS_Helper.flagLogForRetry(logResp.Id);

    //             if(!(Limits.getQueueableJobs() + 1 > Limits.getLimitQueueableJobs())){
    //                 System.enqueueJob(new SYS_ParentingQueueable(String.valueOf(log.Parent__c),SYS_DataCache.INT_TYPE,log));

    //             }
    //         }
    //         else{

    //             //One of the sibling of n children. Save as pending parent
    //             if(log.Requires_process_on_complete__c){
    //                 logResp.Status__c = 'PENDING_PARENT';
    //             }
    //             else{
    //                 logResp.Message__c = 'Record created/updated successfully';
    //                 logResp.Status__c = 'DONE';
                    
    //             }

    //         }
            
    //     }

    //     return logResp;
    // }


    // public override processInboundRecord(SYS_IntegrationLog__c log, Map<SYS_IntegrationLog__c, sObject> mapLogrecVsObject) {
        
    //     String jsonBody = '';
    //     jsonBody =  SYS_Helper.getDataFrom(log); 
    //     jsonBody = preprocessJSONForInbound(log,jsonBody);

    //     if(SYS_DataCache.integrationSetting.get(SYS_DataCache.INT_TYPE).Notifications_are_partial__c && 
    //         log.Is_Notification_Only__c
    //         ){
    //         //String baseEndpoint = SYS_DataCache.integrationSetting.get(SYS_Datacache.INT_TYPE).BaseAPIEndPoint__c;
    //         String getURLPattern = SYS_DataCache.integrationSetting.get(SYS_Datacache.INT_TYPE).GET_URL_Pattern__c;
            
    //         SYS_NotificationInterface it = 
    //         (SYS_NotificationInterface)Type.forName(SYS_DataCache.integrationSetting.get(SYS_Datacache.INT_TYPE).Notification_Wrapper__c).newInstance();
            
    //         List<SYS_IntegrationLog__c> insertSysLog = new List<SYS_IntegrationLog__c>();

    //         for(Map<String,String> rMap:it.getIterator(jsonBody)){
    //             String getURL = getURLPattern;
    //             SYS_IntegrationLog__c  newSysLog = new SYS_IntegrationLog__c();
    //             for(String key:rMap.keySet()){
    //                 getURL = getURL.replaceAll('\\{'+key+'\\}',rMap.get(key));
  
    //             }
    //             /*--*/SYS_debug.log('=============== '+ getURL);

    //             newSysLog.Status__c = SYS_Constants.NEW_STATUS;
    //             newSysLog.HTTP_Method__c = 'GET';
    //             newSysLog.Callout_URL__c = getURL;
    //             newSysLog.Type__c = SYS_Constants.OUTBOUND;
    //             newSysLog.WhatId__c = log.Id;
    //             newSysLog.Integration_Setting__c = SYS_DataCache.INT_TYPE;
    //             newSysLog.SYS_Operation_Type__c = 'UPSERT';
    //             newSysLog.How_to_process__c = 'use_custom_apex_handler';
    //             newSysLog.Custom_Apex_Handler__c = SYS_DataCache.integrationSetting.get(SYS_DataCache.INT_TYPE).ApexHandler__c;
    //             insertSysLog.add(newSysLog);
    //         }

            
    //         if(insertSysLog.size()>0 && SYS_DataCache.enableCheck.get(SYS_DataCache.INT_TYPE.toUpperCase())){
    //             SYS_Helper.insertLog(insertSysLog);
    //         }

    //         // return true;

    //     }
    //     else{
    //         String resource = getResourceFromJSON(log,jsonBody);
    //         log.Resource__c = resource;
    //         SYS_debug.log('\n\n ------------------------------- \n\n Application Service resource:'+resource);

    //         List<sObject> sObjectsToDML = transformJsonToSObject(jsonBody, resource, log);

    //         SYS_debug.log('\n\n ------------------------------- \n\n Application Service sObjects to DML:'+sObjectsToDML);
    //         SYS_debug.log('\n\n ------------------------------- \n\n Application Service externalKeyByResourceMap:'+SYS_DataCache.externalKeyByResourceMap);

    //         String externalIdFieldAPIName = SYS_DataCache.externalKeyByResourceMap.get(resource);
    //         //String externalIdFieldAPIName = log.External_Id_Field_API_Name__c!=NULL?log.External_Id_Field_API_Name__c:'';
            
    //         for(sObject item: sObjectsToDML) {
    //             try {
    //                 item.put('Last_Processed_SYSLog__c', log.Id);
    //             } catch(Exception e) {
    //                 throw new SYS_IntegrationUtilityException('Last Processed SYSLog field is not implemented : \n '+e.getMessage());
    //             }
    //             if(log.WhatId__c != NULL) {
    //                 item.put('Id', log.WhatId__c);
    //             }
    //         }
    //         if(sObjectsToDML.size() > 0)
    //             mapLogrecVsObject.put(log, sObjectsToDML[0]);
    //     }
    //     return ;
    // }

    // ############## OUTBOUND #######################

    // public List<SYS_IntegrationLog__c> generatelogForOutboundResultNew(HttpResponse resp,SYS_IntegrationLog__c log ){

    //     SYS_IntegrationLog__c logResp = SYS_Helper.getLogsToInsert(resp.getBody());

    //     String algo = SYS_DataCache.integrationSetting.get(SYS_DataCache.INT_TYPE).Hashing_Algo__c;
    //     if(algo!=NULL && algo!='')
    //         logResp.Request_Digest__c = generateHash(resp.getBody(),algo);

    //     logResp.Force_Sync__c = log.Force_Sync__c;

    //     if(resp.getStatusCode() != 201 && resp.getStatusCode() != 200){

    //         SYS_debug.log('#### resp status: '+resp.getStatus());
    //         SYS_debug.log('#### resp code: '+resp.getStatusCode()); 
    //         SYS_debug.log('#### resp: '+resp.getBody());

    //         log.Status__c = 'FAIL';
    //         if(!log.Force_Sync__c)
    //             log.retry__c = true;

    //         logResp.Status__c = 'ERROR';
            
    //         logresp.SYS_Http_Status__c = Integer.valueOf(resp.getStatusCode());
    //         logResp.WhatId__c = log.WhatId__c;
    //         logResp.Type__c = SYS_Constants.RESPONSE;
    //         logResp.How_To_Process__c = 'ignore_log';
    //         logResp.Integration_Setting__c = SYS_DataCache.INT_TYPE;
            
    //     }
    //     else{
    //         log.Status__c = 'DONE';

    //         if(log.SYS_Operation_Type__c == 'INSERT' || log.Force_Sync__c){
    //             logResp.Status__c = SYS_Constants.NEW_STATUS;
    //             logResp.SYS_Operation_Type__c = 'UPDATE';
    //             logResp.Flat_Key_for_Resource__c = SYS_DataCache.integrationSetting.get(SYS_DataCache.INT_TYPE).Flat_Key_for_Resource_Response__c;

    //             if(SYS_DataCache.OBJ_TYPE!=NULL)
    //                 logResp.Resource__c = SYS_DataCache.objectSettingMap.get(SYS_DataCache.OBJ_TYPE).Resource_Name__c;
                
    //             logResp.How_To_Process__c = 'use_custom_apex_handler';
    //             logResp.Custom_Apex_Handler__c = SYS_DataCache.integrationSetting.get(SYS_DataCache.INT_TYPE).ApexHandler__c;
            
    //         }
    //         else{

                
    //             if(SYS_DataCache.OBJ_TYPE != NULL && SYS_DataCache.objectSettingMap.get(SYS_DataCache.OBJ_TYPE).Always_Ignore_Response__c){
    //                     logResp.How_To_Process__c = 'ignore_log';
    //                     logResp.Status__c = 'DONE';
    //             }
    //             else{
    //                 logResp.SYS_Operation_Type__c = 'UPSERT';
    //                 logResp.How_To_Process__c = 'use_custom_apex_handler';
    //                 logResp.Custom_Apex_Handler__c = SYS_DataCache.integrationSetting.get(SYS_DataCache.INT_TYPE).ApexHandler__c;
    //             }
    //             //logResp.Status__c = 'DONE';
    //             //logResp.How_To_Process__c = 'ignore_log';

    //         }
        
    //         logresp.SYS_Http_Status__c = Integer.valueOf(resp.getStatusCode());
    //         logResp.WhatId__c = log.WhatId__c;
    //         logResp.Type__c = SYS_Constants.RESPONSE;
    //         logResp.Integration_Setting__c = SYS_DataCache.INT_TYPE;
    //         logResp.ObjectSettingId__c = log.ObjectSettingId__c;
            
    //     }

    //     //doDML(new List<SYS_IntegrationLog__c>{log}, 'UPSERT', '') ;
    //     // ##SYS_Helper.upsertLog(new List<SYS_IntegrationLog__c>{log});
        
    //     logResp.SYS_RequestId__c = log.Id;

    //     return new List<SYS_IntegrationLog__c> {log, logResp};
    // }

}