force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data0__c.field-meta.xml
<CustomField>
    <fullName>data0__c</fullName>
    <label>data0</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/How_to_process__c.field-meta.xml
<CustomField>
    <fullName>How_to_process__c</fullName>
    <label>How to process?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>use_object_setting</fullName>
                <default>true</default>
                <label>Use Object Setting</label>
            </value>
            <value>
                <fullName>use_custom_apex_handler</fullName>
                <label>Use Custom Apex Handler</label>
            </value>
            <value>
                <fullName>ignore_log</fullName>
                <label>Ignore Log</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;NEW&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>CALLOUT ERROR</label>
            </value>
            <value>
                <fullName>PENDING_PARENT</fullName>
                <label>PENDING PARENT</label>
            </value>
            <value>
                <fullName>READY_FOR_PROCESSING</fullName>
                <label>READY FOR PROCESSING</label>
            </value>
            <value>
                <fullName>ENQUEUED_FOR_RETRY</fullName>
                <label>ENQUEUED FOR RETRY</label>
            </value>
            <value>
                <fullName>READY_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>READY_FOR_PARENT</label>
            </value>
            <value>
                <fullName>WAITING_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>WAITING_FOR_PARENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_Tracker__c/SYS_Tracker__c.object-meta.xml
<CustomObject>
    <label>SYS_Tracker</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>SYS_Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_Tracker__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UUID</fullName>
            </value>
            <value>
                <fullName>Display Pic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_Tracker__c/fields/Valid_till__c.field-meta.xml
<CustomField>
    <fullName>Valid_till__c</fullName>
    <label>Valid till</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SYS_Tracker__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <externalId>true</externalId>
    <label>WhatId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_Tracker__c/fields/WhoId__c.field-meta.xml
<CustomField>
    <fullName>WhoId__c</fullName>
    <label>WhoId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ImageController.cls
public with sharing class ImageController {
    @AuraEnabled
    public static void createSysTrackRecord(String recordId, String contentDocumentId) { 
        SYS_IntegrationLog__c errorLog = new SYS_IntegrationLog__c();
        List< SYS_Tracker__c > sysTrackerList = new List< SYS_Tracker__c >();
        List <ContentDocumentLink> updateFileList = new List <ContentDocumentLink>();

        List<SYS_Tracker__c> existingSysTracker = [SELECT Id, Name, Type__c, WhatId__c, WhoId__c FROM SYS_Tracker__c WHERE WhatId__c =: recordId  LIMIT 1];
        SYS_Tracker__c sysTracker =(!existingSysTracker.isEmpty())? existingSysTracker[0] : new SYS_Tracker__c();
        sysTracker.Type__c = 'Display Pic';
        sysTracker.WhatId__c = recordId;
        sysTracker.WhoId__c = contentDocumentId;
        //sysTracker.Valid_till__c = Now() + 865; 
        sysTrackerList.add(sysTracker);
        
        //Obtains all Related/Relevant Files for Selected Record
        List <ContentDocumentLink> relatedFiles = [SELECT ContentDocumentId, LinkedEntityId, ShareType, Visibility 
                                                    FROM ContentDocumentLink 
                                                    WHERE LinkedEntityId = :recordId AND Visibility != 'AllUsers']; 

        for  (Integer i = 0; i < relatedFiles.size(); i++) {
            if (relatedFiles[i].ContentDocumentId == contentDocumentId) {
                relatedFiles[i].Visibility = 'AllUsers';
                updateFileList.add(relatedFiles[i]);
            }
        } 

        try {
            upsert sysTracker;
            System.debug('SYS_Tracker Record Created Successfully: ' + sysTracker.Id);
            if (updateFileList.size() > 0) {
                update updateFileList;
            }
            
        } catch (Exception e) {
            System.debug('Error in Storing SYS_Tracker: ' + e.getMessage());
            //Generate a Log record
            errorLog.data0__c = 'Exception Type: ' + e.getTypeName() + ' Exception Message: ' + e.getMessage();
            errorLog.Status__c = 'ERROR';
            errorLog.How_To_Process__c = 'ignore_log';
        }
        if (errorLog != new SYS_IntegrationLog__c()) {
            insert errorLog;
        }

       // return sysTracker.Id;
    }
    @AuraEnabled
    public static String getSysTrackRecordDocumentId(String recordId) { 
        //SYS_Tracker__c sysTracker = Database.query('SELECT '+ SYS_Helper.getAllFieldsFor('SYS_Tracker__c') + '  WHERE WhatId__c =' + '\'' + recordId+'\'' + ' LIMIT 1 ' + '\')');
        List<SYS_Tracker__c> sysTrackerList = [SELECT Id, Name, Type__c, WhatId__c, WhoId__c FROM SYS_Tracker__c WHERE WhatId__c =: recordId AND (Type__c = 'Display Pic')];
        SYS_Tracker__c sysTracker = ( sysTrackerList.size()>0) ? sysTrackerList[0] : new SYS_Tracker__c() ;
        return sysTracker.WhoId__c;
    }
    @AuraEnabled
    public static String getSysTrackRecordPictureURL(String recordId) { 
        String pictureURL;
        SYS_Tracker__c sysTracker = new SYS_Tracker__c();
        ContentVersion cvRecord = new ContentVersion();
        //sysTracker = Database.query('SELECT '+ SYS_Helper.getAllFieldsFor('SYS_Tracker__c') + '  WHERE WhatId__c =' + '\'' + recordId+'\'' + ' LIMIT 1 ' + '\')');
        List<SYS_Tracker__c> sysTrackerList = [SELECT Id, Name, Type__c, WhatId__c, WhoId__c FROM SYS_Tracker__c WHERE WhatId__c =: recordId AND (Type__c = 'Display Pic') ];
        sysTracker = ( sysTrackerList.size()>0) ? sysTrackerList[0] : new SYS_Tracker__c() ;
        System.debug('( sysTracker!=NULL )' + ( sysTracker!=NULL ));
        System.debug('sysTracker ' + sysTracker);
        if( sysTracker != NULL ){
            try{
                cvRecord = [SELECT Id, ContentDocumentId from ContentVersion where ContentDocumentId =:sysTracker.WhoId__c LIMIT 1];
            } catch(Exception e){
                cvRecord =new ContentVersion();
            }
            System.debug('( sysTracker.WhoId__c !=NULL )' + ( sysTracker.WhoId__c !=NULL ));
            System.debug('cvRecord ' + cvRecord);
            if(cvRecord.Id !=NULL){
                pictureURL='/sfc/servlet.shepherd/version/download/' + cvRecord.Id;
            } else{
                pictureURL = 'noimage';
            }
            System.debug('pictureURL ' + pictureURL);
            
        } else {
            pictureURL = 'noimage';
        }    

        return ( String.IsNotBlank(pictureURL) )? pictureURL : 'noimage';
    }
    public static String getShortendImageName(String nameToShortend){
        List<String> nameArray = nameToShortend.split(' ');
        String newNameShortend = '';
        for (String word : nameArray)
        {
            newNameShortend += word.substring(0,1).toUpperCase();
        }
        newNameShortend = String.isBlank(newNameShortend)?'NA':(newNameShortend.length()>3)? newNameShortend.substring(0,4) : newNameShortend ;
        System.debug('Original Name:- ' + nameToShortend + ' Short Name:- ' + newNameShortend);
        return newNameShortend;
    }
}