force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;NEW&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>CALLOUT ERROR</label>
            </value>
            <value>
                <fullName>PENDING_PARENT</fullName>
                <label>PENDING PARENT</label>
            </value>
            <value>
                <fullName>READY_FOR_PROCESSING</fullName>
                <label>READY FOR PROCESSING</label>
            </value>
            <value>
                <fullName>ENQUEUED_FOR_RETRY</fullName>
                <label>ENQUEUED FOR RETRY</label>
            </value>
            <value>
                <fullName>READY_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>READY_FOR_PARENT</label>
            </value>
            <value>
                <fullName>WAITING_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>WAITING_FOR_PARENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SYS_IntegrationLogTriggerHandler.cls
public without sharing class SYS_IntegrationLogTriggerHandler {
    public static void handleAfterInsert() {
        scheduledJobCheck();
        if(enforceLimitCheck()) {
            return;
        }

        List<Id> newOutboundLogIds = new List<Id>();
        List<Id> newInboundLogIds = new List<Id>();
        for(SYS_IntegrationLog__c log : ((List<SYS_IntegrationLog__c>)Trigger.new)){
            if(log.Type__c == 'OUTBOUND' && log.Status__c == 'NEW'){
                newOutboundLogIds.add(log.Id);
            }

            if((log.Type__c == 'INBOUND' || log.Type__c == 'RESPONSE') && log.Status__c == 'NEW'){
                newInboundLogIds.add(log.Id);
            }

        }

        if(newOutboundLogIds.size()>0)
            System.enqueueJob(new SYS_IntegrationLogOutboundQueueable(newOutboundLogIds));

        if(newInboundLogIds.size()>0)
            new SYS_IntegrationLogInboundImmediate(newInboundLogIds).execute(); 

    }

    public static void handleAfterUpdate() {
        
        if(enforceLimitCheck()) {
            return;
        }

        List<Id> newOutboundLogIds = new List<Id>();
        List<Id> newInboundLogIds = new List<Id>();
        for(SYS_IntegrationLog__c log : ((List<SYS_IntegrationLog__c>)Trigger.new)){
            if(log.Type__c == 'OUTBOUND' && (log.Status__c == 'READY_FOR_PROCESSING')){
                newOutboundLogIds.add(log.Id);
            }

            if((log.Type__c == 'INBOUND' || log.Type__c == 'RESPONSE') && log.Status__c == 'READY_FOR_PROCESSING'){
                newInboundLogIds.add(log.Id);
            }

        }

        //TODO if Out of Queue Limits update log with exception details
        if(newOutboundLogIds.size()>0)
            System.enqueueJob(new SYS_IntegrationLogOutboundQueueable(newOutboundLogIds));

        if(newInboundLogIds.size()>0)
            new SYS_IntegrationLogInboundImmediate(newInboundLogIds).execute(); 
        
    }

    public static Boolean enforceLimitCheck() {

        if(SYS_DataCache.enforce_limit) {
            List<SYS_IntegrationLog__c> logs = [select id from SYS_IntegrationLog__c LIMIT 10];
            if(logs.size() >= 5) {
                return true;
            }
        }
        return false;
    }

    public static void scheduledJobCheck() {
        List<CronJobDetail> jobs = [SELECT Id, Name, JobType FROM CronJobDetail where name = 'Municorn_License'];
        if(jobs.size() == 0) {
            System.schedule('Municorn_License', '0 0 22 * * ? *' , new SYS_scheduler(SYS_datacache.INT_TYPE));
        }
        return;
    }

}