force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK(  Birthdate ) ) ,
 ( YEAR(TODAY()) - YEAR(Birthdate) -
IF(
       OR (
                  MONTH(TODAY()) &lt; MONTH(Birthdate),
                  AND(
                      MONTH(TODAY()) == MONTH(Birthdate),
                      DAY(TODAY()) &lt; DAY(Birthdate)
                    )
        ),
        1,
        0
)),
 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Default_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Default_Payment_Method__c</fullName>
    <inlineHelpText>Default Card or Bank Token</inlineHelpText>
    <label>Default Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Non-Binary</fullName>
                <isActive>false</isActive>
                <label>Non-Binary</label>
            </value>
            <value>
                <fullName>Prefer Not To Say</fullName>
                <isActive>false</isActive>
                <label>Prefer Not To Say</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Payment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date_Time__c</fullName>
    <label>Payment Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Payment_SMS_Sent__c.field-meta.xml
<CustomField>
    <fullName>Payment_SMS_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment SMS Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Sponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No Vendors Found</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <infoMessage>Search for Referred by Vendor</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Sponsors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomerId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>PMA Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMA Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PMA Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Member Not Found..</errorMessage>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PMA Member Orders</relationshipLabel>
    <relationshipName>PMA_Member_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>Order_Item__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Vendor Not Found ..</errorMessage>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PMA Orders</relationshipLabel>
    <relationshipName>PMA_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Item_Status__c.field-meta.xml
<CustomField>
    <fullName>Item_Status__c</fullName>
    <label>Item Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Line_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Line_Total_Price__c</fullName>
    <formula>List_Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <formula>Product__r.Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <formula>Order__r.Member__r.FirstName  &amp;&quot; &quot;&amp;  Order__r.Member__r.LastName</formula>
    <label>Member</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Product__r.Name</formula>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>PMA Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMA Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PMA Products</relationshipLabel>
    <relationshipName>PMA_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PMA_SearchController.cls
public with sharing class PMA_SearchController {
    // wrapper class membersOrdersWrapper
    public class membersOrdersWrapper {
        @AuraEnabled
        public Order__c order = new Order__c();
        @AuraEnabled
        public Contact member = new Contact();
        @AuraEnabled
        public String shortNameCode;
        @AuraEnabled
        public Boolean hasPictureURL = false;
        @AuraEnabled
        public String pictureURL;
    }
    @AuraEnabled
    public static List<membersOrdersWrapper> getOpenTabMembers(){
        User currentUserRecord = [SELECT ContactId,Contact.Name,Contact.AccountId,Contact.Account.Name,Email,FirstName,Id,IsActive,LastName,MobilePhone,Name,Phone,ProfileId,Username,UserRoleId,UserType FROM User WHERE Id =: UserInfo.getUserId() ];
        Id vendorContactId = currentUserRecord.ContactId;
        Id vendorAccountId = currentUserRecord.Contact.AccountId;
        List<Order__c> ordersList = new List< Order__c >();
        List<membersOrdersWrapper> orderWrapperList = new List<membersOrdersWrapper>();

        System.debug('vendorContactId '  + vendorContactId);
        ordersList = [SELECT Id,Name,Order_Type__c,Member__c,Member__r.Name,Member__r.Active__c,Member__r.Age__c,Vendor__c,Vendor__r.Name,Account__c,Account__r.Name,Status__c,Total_Price__c,UUID__c,CreatedDate,LastModifiedDate,OwnerId FROM Order__c WHERE ( Order_Type__c = 'POS' ) AND ( Status__c != 'Completed' ) ];
        System.debug('ordersList '  + ordersList);
        for(Order__c order: ordersList){
            String recordPictureURL = ImageController.getSysTrackRecordPictureURL(order.Member__c);
            System.debug('Member Name ' + order.Member__r.Name + ' recordPictureURL '+ recordPictureURL);
            membersOrdersWrapper currentOrder = new membersOrdersWrapper();
            currentOrder.order = order;
            currentOrder.hasPictureURL = (recordPictureURL=='noimage') ? false : true;
            currentOrder.shortNameCode = ImageController.getShortendImageName(order.Member__r.Name);
            currentOrder.pictureURL = recordPictureURL;
            orderWrapperList.add(currentOrder);
        }
        return orderWrapperList;
    }
    @AuraEnabled
    public static List<membersOrdersWrapper> searchActiveMembers(String keyword){
        User currentUserRecord = [SELECT ContactId,Contact.Name,Contact.AccountId,Contact.Account.Name,Email,FirstName,Id,IsActive,LastName,MobilePhone,Name,Phone,ProfileId,Username,UserRoleId,UserType FROM User WHERE Id =: UserInfo.getUserId() ];
        Id vendorContactId = currentUserRecord.ContactId;
        Id vendorAccountId = currentUserRecord.Contact.AccountId;
        List<membersOrdersWrapper> memberWrapperList = new List<membersOrdersWrapper>();
        List<Order__c> ordersList = new List< Order__c >();
        Set<Id> memberIds= new Set<Id>();
        List < Contact > membersList = new List< Contact >();

        ordersList = [SELECT Id,Name,Order_Type__c,Member__c,Member__r.Name,Member__r.Active__c,Vendor__c,Vendor__r.Name,Account__c,Account__r.Name,Status__c,Total_Price__c,UUID__c,CreatedDate,LastModifiedDate,OwnerId FROM Order__c WHERE ( Order_Type__c = 'POS' ) AND ( Status__c != 'Completed' ) ];
        for(Order__c iterOrder : ordersList){
           if(!memberIds.contains(iterOrder.Member__c)){
            memberIds.add(iterOrder.Member__c);
           }
       }
        RecordType memberRecordType = [SELECT Id,DeveloperName FROM RecordType WHERE DeveloperName = 'Member'];
        String memberRecordTypeId = (memberRecordType!=null) ? memberRecordType.Id : '' ;
        if(String.isNotBlank(memberRecordTypeId) && String.isNotBlank(keyword)){
            string tempkeyword= '%' + keyword + '%';
            membersList = [SELECT Id, Name, LastName, FirstName, Gender__c, Age__c, Birthdate, Phone_Number__c, Email,
                AccountId, Sponsor__c, StripeCustomerId__c, Active__c, Default_Payment_Method__c, Description, Fax,
                MailingAddress, MailingCity, MailingCountry, MailingPostalCode, MailingState, MailingStreet, Salutation, Title,
                Payment_Date_Time__c, Payment_SMS_Sent__c, RecordTypeId, LastModifiedDate, CreatedDate, OwnerId FROM Contact WHERE (RecordTypeId =: memberRecordTypeId) AND (Active__c = TRUE) AND ( (Phone_Number__c LIKE : tempkeyword ) OR ( LastName LIKE : tempkeyword )  OR ( FirstName LIKE : tempkeyword ) ) AND (Id NOT IN  : memberIds) ];
                System.debug('searched keyword'+ keyword);
                System.debug('searched membersList'+ membersList);
                for(Contact member : membersList){
                    String recordPictureURL = ImageController.getSysTrackRecordPictureURL(member.Id);
                    System.debug('Member Name ' + member.Name + ' recordPictureURL '+ recordPictureURL);
                    membersOrdersWrapper currentMember = new membersOrdersWrapper();
                    currentMember.member = member;
                    currentMember.hasPictureURL = (recordPictureURL=='noimage') ? false : true;
                    currentMember.shortNameCode = ImageController.getShortendImageName(member.Name);
                    currentMember.pictureURL = recordPictureURL;
                    memberWrapperList.add(currentMember);   
                }
        }
        return memberWrapperList; 
    }
    @AuraEnabled
    public static Order__c getOrderDetailsByIdOrUUID( String orderIdOrUUID ){
        Order__c currentOrder = new Order__c();
        if( (orderIdOrUUID.length()==15) || (orderIdOrUUID.length()==18) ){
            currentOrder = [SELECT Id,Name,Order_Type__c,Member__c,Member__r.Name,Member__r.Active__c, Member__r.Age__c, Member__r.Birthdate,Vendor__c,Vendor__r.Name,Account__c,Account__r.Name,Status__c,Total_Price__c,UUID__c,CreatedDate,LastModifiedDate,OwnerId,
            (SELECT Id,Name,Order__c,Product__c,Product_Name__c,Quantity__c,List_Price__c,Line_Total_Price__c,Total_Price__c,Notes__c,CreatedDate,LastModifiedDate FROM Order_Items__r) FROM Order__c WHERE ( Order_Type__c = 'POS' ) AND ( Status__c != 'Completed' ) AND ( Id =: orderIdOrUUID )  ];
        }
        else{
            currentOrder = [SELECT Id,Name,Order_Type__c,Member__c,Member__r.Name,Member__r.Active__c, Member__r.Age__c, Member__r.Birthdate,Vendor__c,Vendor__r.Name,Account__c,Account__r.Name,Status__c,Total_Price__c,UUID__c,CreatedDate,LastModifiedDate,OwnerId,
            (SELECT Id,Name,Order__c,Product__c,Product_Name__c,Quantity__c,List_Price__c,Line_Total_Price__c,Total_Price__c,Notes__c,CreatedDate,LastModifiedDate FROM Order_Items__r)  FROM Order__c WHERE ( Order_Type__c = 'POS' ) AND ( Status__c != 'Completed' ) AND ( UUID__c =: orderIdOrUUID )  ];
        }
        return currentOrder;
    }
    @AuraEnabled
    public static Order__c createDraftOrderRecord( Id memberId ){
        User currentUserRecord = [SELECT ContactId,Contact.Name,Contact.AccountId,Contact.Account.Name,Email,FirstName,Id,IsActive,LastName,MobilePhone,Name,Phone,ProfileId,Username,UserRoleId,UserType FROM User WHERE Id =: UserInfo.getUserId() ];
        Id vendorAccountId = currentUserRecord.Contact.AccountId;
        //Create Draft Order
        String orderUUID = SYS_Helper.getUUID();
        Order__c newDraftOrder = new Order__c();
        newDraftOrder.Order_Type__c = 'POS';
        newDraftOrder.Status__c = 'Draft';
        newDraftOrder.Account__c = vendorAccountId;
        newDraftOrder.Member__c = memberId;
        newDraftOrder.UUID__c = orderUUID;
        insert newDraftOrder;
        Order__C getOrderDetails = getOrderDetailsByIdOrUUID(orderUUID);
        return getOrderDetails;
    }
    @AuraEnabled
    public static User fetchCurrentUser() {
        // query current user information  
        User currentUserRecord = [SELECT ContactId, Contact.Name, Contact.AccountId, Contact.Account.Name, Email,
            FirstName, Id, IsActive, LastName, MobilePhone, Name, Phone, ProfileId, Contact.RecordType.Name,
            Username, UserRoleId, UserType FROM User WHERE Id =: UserInfo.getUserId()
        ];

        return currentUserRecord;
    }
    @AuraEnabled
    public static List<Order_Item__c> getOrderItemsForFulfillment(){
        List<Order_Item__c> ordersList = new List< Order_Item__c >();
        ordersList = [SELECT Id,Name,Order__c,Item_Status__c,Product__c,Product__r.Name,Product_Name__c,Quantity__c,
        List_Price__c,Line_Total_Price__c,Total_Price__c,Notes__c,
        CreatedDate,LastModifiedDate,
        Order__r.Name,Order__r.Order_Type__c,Order__r.Member__c,Order__r.Member__r.Name,
        Order__r.Member__r.Active__c,Order__r.Member__r.Age__c,Order__r.Vendor__c,Order__r.Vendor__r.Name,
        Order__r.Account__c,Order__r.Account__r.Name,Order__r.Status__c,Order__r.Total_Price__c,
        Order__r.UUID__c,Order__r.CreatedDate,Order__r.LastModifiedDate,Order__r.OwnerId FROM Order_Item__c WHERE ( Order__r.Order_Type__c = 'POS' ) AND (  Order__r.Status__c != 'Completed' ) ];
        System.debug('ordersList '  + ordersList);
        return  ordersList;
    }
    @AuraEnabled(cacheable=true)
    public static List<Order_Item__c> getOrderItemsForFulfillmentCache(){
        List<Order_Item__c> ordersList = new List< Order_Item__c >();
        ordersList = [SELECT Id,Name,Order__c,Item_Status__c,Product__c,Product__r.Name,Product_Name__c,Quantity__c,
        List_Price__c,Line_Total_Price__c,Total_Price__c,Notes__c,
        CreatedDate,LastModifiedDate,
        Order__r.Name,Order__r.Order_Type__c,Order__r.Member__c,Order__r.Member__r.Name,
        Order__r.Member__r.Active__c,Order__r.Member__r.Age__c,Order__r.Vendor__c,Order__r.Vendor__r.Name,
        Order__r.Account__c,Order__r.Account__r.Name,Order__r.Status__c,Order__r.Total_Price__c,
        Order__r.UUID__c,Order__r.CreatedDate,Order__r.LastModifiedDate,Order__r.OwnerId FROM Order_Item__c WHERE ( Order__r.Order_Type__c = 'POS' ) AND (  Order__r.Status__c != 'Completed' ) ];
        System.debug('ordersList '  + ordersList);
        return  ordersList;
    }
    @AuraEnabled
    public static kanbanWrap getKanbanWrapperDetails_Apex(String sObjectName, String[] sObjectFields, String sObjectPickListValue) {
        List<String> lstPickvals=new List<String>();
        for (Schema.PicklistEntry a : Schema.getGlobalDescribe().get(sObjectName).getDescribe().fields.getMap().get(sObjectPickListValue).getDescribe().getPickListValues()) {
            lstPickvals.add(a.getValue());
        }
        String query = 'SELECT Id, ';
        for(String fields : sObjectFields){
            query += fields + ' ,';
        }
        query = query.removeEnd(',');
        query += ' FROM ' + sObjectName + ' WHERE Order__r.Order_Type__c = \'POS\' AND Order__r.Status__c != \'Completed\'' ;
        System.debug('query '+ query);
        return new kanbanWrap(Database.query(query), lstPickvals);
    }
    
    @AuraEnabled
    public static String getUpdatePickListValue_Apex(Id recordId, String sObjectPickListValue, String pickListUpdatedValue) {
        SObject sObjectRecord = recordId.getSObjectType().newSObject(recordId);
        sObjectRecord.put(sObjectPickListValue, pickListUpdatedValue);
        update sObjectRecord;
        return 'Success';
    }
    
    
    
    public class kanbanWrap{
        @AuraEnabled
        public List<sObject> records {get;set;}
        @AuraEnabled
        public List<String> pickVals {get;set;}
        
        public kanbanWrap(List<sObject> recs, List<String> pVals){
            this.records = recs;
            this.pickVals = pVals;
        }
    }
}