force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomerId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/PaymentRequest__c.object-meta.xml
<CustomObject>
    <description>This is a payment request made by a user</description>
    <label>Payment Request</label>
    <nameField>
        <label>Payment Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount for which the payment request is being made</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Item number in the request group</description>
    <label>Item number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Payment_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference_Id__c</fullName>
    <displayFormat>P{0000000000}</displayFormat>
    <label>Payment Reference Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>The type of payment request, either and immediate one time transaction or a subscription</description>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>immediate</fullName>
            </value>
            <value>
                <fullName>subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>payment_new</fullName>
            </value>
            <value>
                <fullName>payment_done</fullName>
            </value>
            <value>
                <fullName>payment_expired</fullName>
            </value>
            <value>
                <fullName>payment_failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/AmountRefunded__c.field-meta.xml
<CustomField>
    <fullName>AmountRefunded__c</fullName>
    <label>AmountRefunded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <label>Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/FailureCode__c.field-meta.xml
<CustomField>
    <fullName>FailureCode__c</fullName>
    <label>Failure code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/FailureMessage__c.field-meta.xml
<CustomField>
    <fullName>FailureMessage__c</fullName>
    <label>Failure reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/PaymentBankLast4Digits__c.field-meta.xml
<CustomField>
    <fullName>PaymentBankLast4Digits__c</fullName>
    <label>Bank Last 4 Digits</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/PaymentBankName__c.field-meta.xml
<CustomField>
    <fullName>PaymentBankName__c</fullName>
    <label>Bank Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/PaymentCardLast4Digits__c.field-meta.xml
<CustomField>
    <fullName>PaymentCardLast4Digits__c</fullName>
    <label>Card Last 4 Digits</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment method used</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/PaymentMethodType__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ach_credit_transfer</fullName>
            </value>
            <value>
                <fullName>ach_debit</fullName>
                <label>ACH</label>
            </value>
            <value>
                <fullName>alipay</fullName>
            </value>
            <value>
                <fullName>bancontact</fullName>
            </value>
            <value>
                <fullName>card</fullName>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>card_present</fullName>
            </value>
            <value>
                <fullName>eps</fullName>
            </value>
            <value>
                <fullName>giropay</fullName>
            </value>
            <value>
                <fullName>ideal</fullName>
            </value>
            <value>
                <fullName>klarna</fullName>
            </value>
            <value>
                <fullName>multibanco</fullName>
            </value>
            <value>
                <fullName>p24</fullName>
            </value>
            <value>
                <fullName>sepa_debit</fullName>
            </value>
            <value>
                <fullName>sofort</fullName>
            </value>
            <value>
                <fullName>stripe_account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/PaymentRequestId__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequestId__c</fullName>
    <description>Parent payment request</description>
    <label>PaymentRequestId</label>
    <referenceTo>PaymentRequest__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>initiated</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>succeeded</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>failed</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/StatusMessage__c.field-meta.xml
<CustomField>
    <fullName>StatusMessage__c</fullName>
    <description>Status message that is received from stripe api charge response</description>
    <label>Status message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/StripeChargeId__c.field-meta.xml
<CustomField>
    <fullName>StripeChargeId__c</fullName>
    <description>Stripe charge id</description>
    <externalId>true</externalId>
    <label>StripeChargeId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Transaction Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionReference__c.field-meta.xml
<CustomField>
    <fullName>TransactionReference__c</fullName>
    <displayFormat>T{0000000000}</displayFormat>
    <label>Transaction Reference Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/uuid__c.field-meta.xml
<CustomField>
    <fullName>uuid__c</fullName>
    <label>uuid</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TransactionService.cls
public class TransactionService {

    public Transaction__c createTransaction(PaymentRequest__c paymentRequest) {
        Transaction__c tx = buildTransaction(paymentRequest);
        
        insert tx;
        return getTransaction(tx.Id);
    }
    
    public Transaction__c getTransaction(String id) {
        return [SELECT Id,
                uuid__c,
                TransactionReference__c,
                Amount__c,
                PaymentRequestId__r.Contact__r.Id,
                PaymentRequestId__r.Email__c,
                PaymentRequestId__r.Contact__r.Name,
                PaymentRequestId__r.Contact__r.StripeCustomerId__c,
                PaymentRequestId__r.Opportunity__r.Id,
                PaymentRequestId__r.Opportunity__r.Name,
                PaymentRequestId__r.Account__r.Name,
                PaymentRequestId__r.PaymentType__c,
                PaymentRequestId__r.Amount__c,
                PaymentRequestId__r.Status__c,
                PaymentRequestId__r.ItemNumber__c,
                PaymentRequestId__r.Payment_Reference_Id__c,
                TransactionDate__c,
                CurrencyCode__c,
                AmountRefunded__c,
                FailureCode__c,
                FailureMessage__c,
                PaymentMethodType__c,
                PaymentMethod__c,
                PaymentCardLast4Digits__c,
                PaymentBankLast4Digits__c,
                PaymentBankName__c,
                Status__c,
                StripeChargeId__c,
                StatusMessage__c
                FROM Transaction__c WHERE Id = :id];
    }

    public Transaction__c getTransactionExtId(String txid) {
        return [SELECT Id,
                uuid__c,
                TransactionReference__c,
                Amount__c,
                PaymentRequestId__r.Contact__r.Id,
                PaymentRequestId__r.Email__c,
                PaymentRequestId__r.Contact__r.Name,
                PaymentRequestId__r.Contact__r.StripeCustomerId__c,
                PaymentRequestId__r.Opportunity__r.Id,
                PaymentRequestId__r.Opportunity__r.Name,
                PaymentRequestId__r.Account__r.Name,
                PaymentRequestId__r.PaymentType__c,
                PaymentRequestId__r.Amount__c,
                PaymentRequestId__r.Status__c,
                PaymentRequestId__r.ItemNumber__c,
                PaymentRequestId__r.Payment_Reference_Id__c,
                TransactionDate__c,
                CurrencyCode__c,
                AmountRefunded__c,
                FailureCode__c,
                FailureMessage__c,
                PaymentMethodType__c,
                PaymentMethod__c,
                PaymentCardLast4Digits__c,
                PaymentBankLast4Digits__c,
                PaymentBankName__c,
                Status__c,
                StripeChargeId__c,
                StatusMessage__c
                FROM Transaction__c WHERE StripeChargeId__c = :txid ORDER BY createddate desc LIMIT 1];
    }

    public Transaction__c getTransactionByUuid(String uuid) {
        return [SELECT Id,
                uuid__c,
                TransactionReference__c,
                Amount__c,
                PaymentRequestId__r.Contact__r.Id,
                PaymentRequestId__r.Email__c,
                PaymentRequestId__r.Contact__r.Name,
                PaymentRequestId__r.Contact__r.StripeCustomerId__c,
                PaymentRequestId__r.Opportunity__r.Id,
                PaymentRequestId__r.Opportunity__r.Name,
                PaymentRequestId__r.Account__r.Name,
                PaymentRequestId__r.PaymentType__c,
                PaymentRequestId__r.Amount__c,
                PaymentRequestId__r.Status__c,
                PaymentRequestId__r.ItemNumber__c,
                PaymentRequestId__r.Payment_Reference_Id__c,
                TransactionDate__c,
                CurrencyCode__c,
                AmountRefunded__c,
                FailureCode__c,
                FailureMessage__c,
                PaymentMethodType__c,
                PaymentMethod__c,
                PaymentCardLast4Digits__c,
                PaymentBankLast4Digits__c,
                PaymentBankName__c,
                Status__c,
                StripeChargeId__c,
                StatusMessage__c
        FROM Transaction__c WHERE uuid__c = :uuid];
    }
    
    public Transaction__c getTransactionByChargeId(String Id) {
       Transaction__c txs = [SELECT Id,
                uuid__c,
                TransactionReference__c,
                Amount__c,
                PaymentRequestId__r.Contact__r.Id,
                PaymentRequestId__r.Email__c,
                PaymentRequestId__r.Contact__r.Name,
                PaymentRequestId__r.Contact__r.StripeCustomerId__c,
                PaymentRequestId__r.Opportunity__r.Id,
                PaymentRequestId__r.Opportunity__r.Name,
                PaymentRequestId__r.Account__r.Name,
                PaymentRequestId__r.PaymentType__c,
                PaymentRequestId__r.Amount__c,
                PaymentRequestId__r.Status__c,
                PaymentRequestId__r.ItemNumber__c,
                PaymentRequestId__r.Payment_Reference_Id__c,
                TransactionDate__c,
                CurrencyCode__c,
                AmountRefunded__c,
                FailureCode__c,
                FailureMessage__c,
                PaymentMethodType__c,
                PaymentMethod__c,
                PaymentCardLast4Digits__c,
                PaymentBankLast4Digits__c,
                PaymentBankName__c,
                Status__c,
                StripeChargeId__c,
                StatusMessage__c
        FROM Transaction__c WHERE StripeChargeId__c = :Id];
        System.debug('test getTransactionByChargeId '+ txs);
        return [SELECT Id,
                uuid__c,
                TransactionReference__c,
                Amount__c,
                PaymentRequestId__r.Contact__r.Id,
                PaymentRequestId__r.Email__c,
                PaymentRequestId__r.Contact__r.Name,
                PaymentRequestId__r.Contact__r.StripeCustomerId__c,
                PaymentRequestId__r.Opportunity__r.Id,
                PaymentRequestId__r.Opportunity__r.Name,
                PaymentRequestId__r.Account__r.Name,
                PaymentRequestId__r.PaymentType__c,
                PaymentRequestId__r.Amount__c,
                PaymentRequestId__r.Status__c,
                PaymentRequestId__r.ItemNumber__c,
                PaymentRequestId__r.Payment_Reference_Id__c,
                TransactionDate__c,
                CurrencyCode__c,
                AmountRefunded__c,
                FailureCode__c,
                FailureMessage__c,
                PaymentMethodType__c,
                PaymentMethod__c,
                PaymentCardLast4Digits__c,
                PaymentBankLast4Digits__c,
                PaymentBankName__c,
                Status__c,
                StripeChargeId__c,
                StatusMessage__c
        FROM Transaction__c WHERE StripeChargeId__c = :Id];
    }
    
    public Transaction__c buildTransaction(PaymentRequest__c paymentRequest) {
        Transaction__c tx = new Transaction__c();
        tx.uuid__c = PMA_ExternalSiteFormsUtility.getUUID();
        tx.PaymentRequestId__c = paymentRequest.Id;
        tx.Status__c = 'initiated';
        tx.Amount__c = paymentRequest.Amount__c;
        tx.CurrencyCode__c = UserInfo.getDefaultCurrency();
        tx.TransactionDate__c = Datetime.now();
        
        return tx;
    }
}