force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>PMA Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMA Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PMA Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/Payment_Gateway__c.object-meta.xml
<CustomObject>
    <label>Payment Gateway</label>
    <nameField>
        <label>Payment Gatway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Gateway__c/fields/Gateway_Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Public_Key__c</fullName>
    <label>Gateway Public Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/Payment_Intent__c.object-meta.xml
<CustomObject>
    <label>Payment Intent</label>
    <nameField>
        <label>Payment Intent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Intents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Intent__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Intents</relationshipLabel>
    <relationshipName>Payment_Intents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Intents</relationshipLabel>
    <relationshipName>Payment_Intents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency	Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/First_Charge_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Charge_Date__c</fullName>
    <label>First Charge Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>single</fullName>
                <default>true</default>
                <label>single</label>
            </value>
            <value>
                <fullName>month</fullName>
            </value>
            <value>
                <fullName>quarter</fullName>
            </value>
            <value>
                <fullName>year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Intents</relationshipLabel>
    <relationshipName>Payment_Intents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Payment Intents</relationshipLabel>
    <relationshipName>Payment_Intents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Gateway</label>
    <referenceTo>Payment_Gateway__c</referenceTo>
    <relationshipLabel>Payment Intents</relationshipLabel>
    <relationshipName>Payment_Intents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Payment_Link__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link__c</fullName>
    <formula>IF( NOT(ISBLANK(UUID__c )) , 
    ( $Label.GuestUserPaymentLink  +  UUID__c) , &quot;&quot;)</formula>
    <label>Payment Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Payment_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference_Id__c</fullName>
    <displayFormat>PI{000000000}</displayFormat>
    <externalId>true</externalId>
    <label>Payment Reference Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>payment_new</fullName>
            </value>
            <value>
                <fullName>payment_done</fullName>
            </value>
            <value>
                <fullName>payment_expired</fullName>
            </value>
            <value>
                <fullName>payment_failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PaymentIntentService.cls
public class PaymentIntentService {

    public static List<Payment_Intent__c> getPaymentRequestByUUID(String uuid) {
        return [SELECT Id,Name,
                Payment_Gateway__c,
                Payment_Gateway__r.Name,
                Payment_Gateway__r.Gateway_Public_Key__c,
                Payment_Gateway__r.Test_Mode__c,
                Account__c,
                Account__r.Name,
                Contact__c,
                Contact__r.Name,
                Contact__r.LastName,
                Contact__r.FirstName,
                Contact__r.Phone_Number__c,
                Contact__r.Email,
                Opportunity__c,
                Opportunity__r.Name,
                Order__c,
                Order__r.Name,
                Amount__c,
                Frequency__c,
                Currency_Code__c,Email__c,First_Charge_Date__c,Payment_Link__c,
                Payment_Reference_Id__c,Payment_Type__c,Status__c,UUID__c FROM Payment_Intent__c WHERE UUID__c = :uuid];
    }

    public static Payment_Intent__c getPaymentIntent(Id id) {
        return [SELECT Id,Name,
                Payment_Gateway__c,
                Payment_Gateway__r.Name,
                Payment_Gateway__r.Gateway_Public_Key__c,
                Payment_Gateway__r.Test_Mode__c,
                Account__c,
                Account__r.Name,
                Contact__c,
                Contact__r.Name,
                Contact__r.LastName,
                Contact__r.FirstName,
                Contact__r.Phone_Number__c,
                Contact__r.Email,
                Opportunity__c,
                Opportunity__r.Name,
                Order__c,
                Order__r.Name,
                Amount__c,
                Frequency__c,
                Currency_Code__c,Email__c,First_Charge_Date__c,Payment_Link__c,
                Payment_Reference_Id__c,Payment_Type__c,Status__c,UUID__c FROM Payment_Intent__c WHERE Id = :id];
    }

    public static Payment_Intent__c createNewPaymentIntent(
            String paymentName,
            Id paymentGatewayId,
            Id contactId,
            Id accountId,
            Id opportunityId,
            Id orderId,
            String paymentType,
            Double amount,
            String email,
            String frequency,
            Date firstChargeDate) {
        System.debug('Payments Intent service, create new Intent for' +
                ', contact Name=' + paymentName +
                ', paymentGateway Id=' + paymentGatewayId +
                ', contact id=' + contactId +
                ', account id=' + accountId +
                ', opportunity id=' + opportunityId +
                ', Order id=' + orderId +
                ', amount=' + amount +
                ', email=' + email +
                ', frequency=' + frequency +
                ', first charge date=' + firstChargeDate);

                Payment_Intent__c paymentIntent = new Payment_Intent__c(
                Name = paymentName,
                Payment_Gateway__c = paymentGatewayId,
                Contact__c = contactId,
                Account__c = accountId,
                Opportunity__c = opportunityId,
                Order__c = orderId,
                Email__c = email,
                Status__c = 'payment_new',
                Payment_Type__c = paymentType,
                Frequency__c = frequency,
                First_Charge_Date__c = firstChargeDate,
                Amount__c = amount,
                Currency_Code__c = UserInfo.getDefaultCurrency(),
                UUID__c = SYS_Helper.getUUID()
        );

        insert paymentIntent;

        return getPaymentIntent(paymentIntent.Id);
    }
}