force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Request_Group__c/Payment_Request_Group__c.object-meta.xml
<CustomObject>
    <description>This is a payment request group for multiple payment requests to be added to cart</description>
    <label>Payment Requests</label>
    <nameField>
        <label>Payment Request Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request_Group__c/fields/uuid__c.field-meta.xml
<CustomField>
    <fullName>uuid__c</fullName>
    <label>uuid</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/PaymentRequest__c.object-meta.xml
<CustomObject>
    <description>This is a payment request made by a user</description>
    <label>Payment Request</label>
    <nameField>
        <label>Payment Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount for which the payment request is being made</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/FirstChargeDate__c.field-meta.xml
<CustomField>
    <fullName>FirstChargeDate__c</fullName>
    <label>First Charge Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>quarter</fullName>
            </value>
            <value>
                <fullName>month</fullName>
            </value>
            <value>
                <fullName>year</fullName>
            </value>
            <value>
                <fullName>single</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Item number in the request group</description>
    <label>Item number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Payment_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference_Id__c</fullName>
    <displayFormat>P{0000000000}</displayFormat>
    <label>Payment Reference Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/PaymentRequests__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequests__c</fullName>
    <label>Payment Requests</label>
    <referenceTo>Payment_Request_Group__c</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>The type of payment request, either and immediate one time transaction or a subscription</description>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>immediate</fullName>
            </value>
            <value>
                <fullName>subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>payment_new</fullName>
            </value>
            <value>
                <fullName>payment_done</fullName>
            </value>
            <value>
                <fullName>payment_expired</fullName>
            </value>
            <value>
                <fullName>payment_failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Status_Message__c.field-meta.xml
<CustomField>
    <fullName>Status_Message__c</fullName>
    <label>Status message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PaymentsService.cls
public class PaymentsService {

    public List<PaymentRequest__c> getPaymentRequestByGroupId(String parentRequestGroupId) {
        return [SELECT Id,
                Email__c,
                Contact__c,
                Contact__r.Id,
                Contact__r.Name,
                Account__c,
                Account__r.Id,
                Account__r.Name,
                Opportunity__c,
                Opportunity__r.Id,
                Opportunity__r.Name,
                Status__c,
                Status_Message__c,
                Currency_Code__c,
                PaymentType__c,
                Amount__c,
                ItemNumber__c,
                Payment_Reference_Id__c,
                Frequency__c,
                FirstChargeDate__c,
                PaymentRequests__c
        FROM PaymentRequest__c WHERE PaymentRequests__r.uuid__c = :parentRequestGroupId];
    }

    public PaymentRequest__c getPaymentRequest(Id id) {
        return [SELECT Id,
                Email__c,
                Contact__c,
                Contact__r.Id,
                Contact__r.Name,
                Account__c,
                Account__r.Id,
                Account__r.Name,
                Opportunity__c,
                Opportunity__r.Id,
                Opportunity__r.Name,
                Status__c,
                Status_Message__c,
                Currency_Code__c,
                PaymentType__c,
                Amount__c,
                ItemNumber__c,
                Payment_Reference_Id__c,
                Frequency__c,
                FirstChargeDate__c,
                PaymentRequests__c,
                PaymentRequests__r.Id,
                PaymentRequests__r.uuid__c
        FROM PaymentRequest__c WHERE Id = :id];
    }

    public PaymentRequest__c createNewPaymentRequest(
            String paymentName,
            Id contactId,
            Id accountId,
            Id opportunityId,
            String paymentType,
            Double amount,
            String email,
            String frequency,
            Date firstChargeDate,
            Integer itemNumber,
            String paymentRequestGroupId) {
        System.debug('Payments service, create new request for' +
                ', contact Name=' + paymentName +
                ', contact id=' + contactId +
                ', account id=' + accountId +
                ', opportunity id=' + opportunityId +
                ', amount=' + amount +
                ', email=' + email +
                ', frequency=' + frequency +
                ', first charge date=' + firstChargeDate);

        List<Payment_Request_Group__c> paymentRequestGroups = [SELECT Id, uuid__c FROM Payment_Request_Group__c WHERE uuid__c=:paymentRequestGroupId];

        Payment_Request_Group__c paymentRequestGroup;
        if (paymentRequestGroups.isEmpty()) {
            paymentRequestGroup = new Payment_Request_Group__c(uuid__c = paymentRequestGroupId);
            insert paymentRequestGroup;
        } else {
            paymentRequestGroup = paymentRequestGroups.get(0);
        }

        PaymentRequest__c paymentRequest = new PaymentRequest__c(
                Email__c = email,
                Name = paymentName,
                Contact__c = contactId,
                Account__c = accountId,
                Opportunity__c = opportunityId,
                Status__c = 'payment_new',
                PaymentType__c = paymentType,
                Frequency__c = frequency,
                ItemNumber__c = itemNumber,
                FirstChargeDate__c = firstChargeDate,
                Amount__c = amount,
                Currency_Code__c = UserInfo.getDefaultCurrency(),
                PaymentRequests__c = paymentRequestGroup.Id
        );

        insert paymentRequest;

        return getPaymentRequest(paymentRequest.Id);
    }
}