force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Request_Group__c/Payment_Request_Group__c.object-meta.xml
<CustomObject>
    <description>This is a payment request group for multiple payment requests to be added to cart</description>
    <label>Payment Requests</label>
    <nameField>
        <label>Payment Request Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request_Group__c/fields/uuid__c.field-meta.xml
<CustomField>
    <fullName>uuid__c</fullName>
    <label>uuid</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/PaymentRequest__c.object-meta.xml
<CustomObject>
    <description>This is a payment request made by a user</description>
    <label>Payment Request</label>
    <nameField>
        <label>Payment Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount for which the payment request is being made</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>quarter</fullName>
            </value>
            <value>
                <fullName>month</fullName>
            </value>
            <value>
                <fullName>year</fullName>
            </value>
            <value>
                <fullName>single</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Item number in the request group</description>
    <label>Item number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/PaymentRequests__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequests__c</fullName>
    <label>Payment Requests</label>
    <referenceTo>Payment_Request_Group__c</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>The type of payment request, either and immediate one time transaction or a subscription</description>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>immediate</fullName>
            </value>
            <value>
                <fullName>subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>payment_new</fullName>
            </value>
            <value>
                <fullName>payment_done</fullName>
            </value>
            <value>
                <fullName>payment_expired</fullName>
            </value>
            <value>
                <fullName>payment_failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Status_Message__c.field-meta.xml
<CustomField>
    <fullName>Status_Message__c</fullName>
    <label>Status message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/SubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionId__c</fullName>
    <label>SubscriptionId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;NEW&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>CALLOUT ERROR</label>
            </value>
            <value>
                <fullName>PENDING_PARENT</fullName>
                <label>PENDING PARENT</label>
            </value>
            <value>
                <fullName>READY_FOR_PROCESSING</fullName>
                <label>READY FOR PROCESSING</label>
            </value>
            <value>
                <fullName>ENQUEUED_FOR_RETRY</fullName>
                <label>ENQUEUED FOR RETRY</label>
            </value>
            <value>
                <fullName>READY_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>READY_FOR_PARENT</label>
            </value>
            <value>
                <fullName>WAITING_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>WAITING_FOR_PARENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>This field is used when the JSON has more than 1M characters and needs to spread over multiple records.</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/AmountRefunded__c.field-meta.xml
<CustomField>
    <fullName>AmountRefunded__c</fullName>
    <label>AmountRefunded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/FailureCode__c.field-meta.xml
<CustomField>
    <fullName>FailureCode__c</fullName>
    <label>Failure code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/FailureMessage__c.field-meta.xml
<CustomField>
    <fullName>FailureMessage__c</fullName>
    <label>Failure reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/PaymentMethodType__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ach_credit_transfer</fullName>
            </value>
            <value>
                <fullName>ach_debit</fullName>
                <label>ACH</label>
            </value>
            <value>
                <fullName>alipay</fullName>
            </value>
            <value>
                <fullName>bancontact</fullName>
            </value>
            <value>
                <fullName>card</fullName>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>card_present</fullName>
            </value>
            <value>
                <fullName>eps</fullName>
            </value>
            <value>
                <fullName>giropay</fullName>
            </value>
            <value>
                <fullName>ideal</fullName>
            </value>
            <value>
                <fullName>klarna</fullName>
            </value>
            <value>
                <fullName>multibanco</fullName>
            </value>
            <value>
                <fullName>p24</fullName>
            </value>
            <value>
                <fullName>sepa_debit</fullName>
            </value>
            <value>
                <fullName>sofort</fullName>
            </value>
            <value>
                <fullName>stripe_account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/PaymentRequestId__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequestId__c</fullName>
    <description>Parent payment request</description>
    <label>PaymentRequestId</label>
    <referenceTo>PaymentRequest__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>initiated</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>succeeded</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>failed</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/StatusMessage__c.field-meta.xml
<CustomField>
    <fullName>StatusMessage__c</fullName>
    <description>Status message that is received from stripe api charge response</description>
    <label>Status message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/StripeChargeId__c.field-meta.xml
<CustomField>
    <fullName>StripeChargeId__c</fullName>
    <description>Stripe charge id</description>
    <externalId>true</externalId>
    <label>StripeChargeId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Transaction Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/uuid__c.field-meta.xml
<CustomField>
    <fullName>uuid__c</fullName>
    <label>uuid</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/Charge.recordType-meta.xml
<RecordType>
    <fullName>Charge</fullName>
    <active>true</active>
    <description>For Authorizations, Charges and Refunds.</description>
    <label>Charge</label>
</RecordType>

force-app/main/default/classes/StripeService.cls
public class StripeService {

    private static StripeRestService stripeRest = new StripeRestService();
    private static TransactionService txnService = new TransactionService();
    private static PaymentsService paymentsService = new PaymentsService();

    public Stripe.PaymentMethods getPaymentMethods(Id contactId) {
        Stripe.PaymentMethods paymentMethods = new Stripe.PaymentMethods();
        try {
            Stripe.Customer cus = getCustomer(contactId);

            paymentMethods.bankAccounts = stripeRest.getBankAccounts(cus.id);
            paymentMethods.cards = stripeRest.getCards(cus.id);

            updateStripeCustomerId(contactId, cus.id);
        } catch (Stripe.RestException ex) {
            System.debug('Stripe error=' + ex.errorResponse);
        }
        return paymentMethods;
    }

    public Stripe.Payments processPayments(List<PaymentRequest__c> paymentRequests, Stripe.UserPaymentRequest request) {
        List<TxnResponseWrapper> txnResponses = new List<TxnResponseWrapper>();
        List<PaymentRequest__c> paymentRequestsResponse = new List<PaymentRequest__c>();

        Stripe.Payments payments = new Stripe.Payments();

        Id contactId = paymentRequests[0].Contact__c;
        Stripe.Customer customer = getCustomer(contactId);

        String stripeCustomerId = customer.id;
		System.debug('test paymentRequests proceess'+paymentRequests);
        System.debug('test customer proceess'+customer);
         System.debug('test stripeCustomerId proceess'+stripeCustomerId);
        String source = getSource(stripeCustomerId, request);
		System.debug('test source proceess'+source);
        for (PaymentRequest__c paymentRequest : paymentRequests) {
            if (paymentRequest.PaymentType__c == 'immediate') {
                Stripe.ErrorResponse error;
                Stripe.Charge charge = new Stripe.Charge();
                try {
                    String currencyType = UserInfo.getDefaultCurrency();
                    System.debug('Current currency=' + currencyType);
                    Long amount = getAmount(paymentRequest.Amount__c);
                    System.debug('test paymentRequest.Amount__c proceess'+paymentRequest.Amount__c);
                    System.debug('test amount proceess'+amount);
                    String description = 'Payment';

                    Map<String, Object> metadata = new Map<String, Object>();
                    metadata.put('opportunityId', paymentRequest.Opportunity__c);
                    metadata.put('contactId', paymentRequest.Contact__c);
                    metadata.put('accountId', paymentRequest.Account__c);
                    metadata.put('transactionId', paymentRequest.Id);
                    //metadata.put('uuid', paymentRequest.PaymentRequests__r.uuid__c);

                    charge = stripeRest.charge(amount, currencyType, description, source, metadata);
                } catch (Stripe.RestException ex) {
                    error = ex.errorResponse;
                }
                //Changed to Municorn Get Record
                Transaction__c txn = txnService.buildTransaction(paymentRequest);
                System.debug('test Charge Id '+charge.Id);
                //Transaction__c txn = txnService.getTransactionByChargeId(charge.Id);

                TxnResponseWrapper txnResponseWrapper = new TxnResponseWrapper();
                txnResponseWrapper.charge = charge;
                txnResponseWrapper.error = error;
                txnResponseWrapper.txn = txn;
                txnResponseWrapper.paymentRequest = paymentRequest;

                txnResponses.add(txnResponseWrapper);
                paymentRequestsResponse.add(paymentRequest);
            } else if (paymentRequest.PaymentType__c == 'subscription') {
                Double amount = paymentRequest.Amount__c;
                String interval = paymentRequest.Frequency__c;

                try {
                    Stripe.Product product = stripeRest.createProduct('defaultProduct');
                    Stripe.Plan plan = stripeRest.createPlan(getAmount(amount), UserInfo.getDefaultCurrency(), interval, product.name);

                    Stripe.Subscription subscription = stripeRest.createSubscription(plan.id, customer.id, paymentRequest);
                    paymentRequest.SubscriptionId__c = subscription.id;
                } catch (Stripe.RestException ex) {
                    Stripe.Error error = ex.errorResponse.error;
                    paymentRequest.Status__c = 'payment_failed';
                    paymentRequest.Status_Message__c = error.message;
                }
                if (paymentRequest.ItemNumber__c == null) {
                    paymentRequest.ItemNumber__c = 1;
                }
                paymentRequestsResponse.add(paymentRequest);
            }
        }
		//Todo get record details into  payments Wrapper
        for (TxnResponseWrapper txnResponse: txnResponses) {
            postProcessPayment(txnResponse.txn, txnResponse.paymentRequest, txnResponse.error, txnResponse.charge);
            // System.debug('item no='+txnService.getTransactionExtId(txnResponse.charge.id).PaymentRequestId__r.ItemNumber__c);
            System.debug('test txnResponse proceess '+txnResponse);
            System.debug('test txnResponse.charge.id proceess '+txnResponse.charge.id);
            //payments.registerPayment(txnService.getTransactionExtId(txnResponse.charge.id)); 
        }
        // update paymentRequestsResponse;
        // Todo Fix get Record details into  payments Wrapper
        for (PaymentRequest__c paymentRequest: paymentRequestsResponse) {
            System.debug('pymt id'+paymentRequest.Id);
            payments.registerPayment(paymentsService.getPaymentRequest(paymentRequest.Id));
        }
        payments.payments.sort();

        return payments;
    }

    public class TxnResponseWrapper {
        public Transaction__c txn;
        public PaymentRequest__c paymentRequest;
        public Stripe.ErrorResponse error;
        public Stripe.Charge charge;
    }

    private String getSource(String stripeCustomerId, Stripe.UserPaymentRequest request) {
        String paymentSource = request.selectedPaymentSource;
        String stripeToken = request.stripeToken == null ? request.bankToken : request.stripeToken;
        if (request.paymentMethod == 'new-card' && request.saveCard) {
            Stripe.Card card = registerCard(stripeToken, stripeCustomerId);
            paymentSource = card.id;
        }
        String source = '&customer=' + stripeCustomerId + '&source=' + paymentSource;
        source = String.isBlank(paymentSource) ? '&source=' + stripeToken: ('&customer=' + stripeCustomerId + '&source=' + paymentSource);
        return source;
    }

    public void charge(Transaction__c txn, Stripe.UserPaymentRequest request) {
        Stripe.ErrorResponse error;
        Stripe.Charge charge = new Stripe.Charge();
        String paymentSource = request.selectedPaymentSource;
        String stripeToken = request.stripeToken == null ? request.bankToken : request.stripeToken;
        try {
            Stripe.Customer customer = getCustomer(txn.PaymentRequestId__r.Contact__r.Id);

            String stripeCustomerId = customer.id;

            if (request.paymentMethod == 'new-card' && request.saveCard) {
                Stripe.Card card = registerCard(stripeToken, stripeCustomerId);
                paymentSource = card.id;
            }
            String source = '&customer=' + stripeCustomerId + '&source=' + paymentSource;
            source = String.isBlank(paymentSource) ? '&source=' + stripeToken: ('&customer=' + stripeCustomerId + '&source=' + paymentSource);

            String currencyType = UserInfo.getDefaultCurrency();
            System.debug('Current currency=' + currencyType);
            Long amount = getAmount(txn.Amount__c);
            String description = 'Payment';

            Map<String, Object> metadata = new Map<String, Object>();
            metadata.put('opportunityId', txn.PaymentRequestId__r.Opportunity__r.Id);
            metadata.put('contactId', txn.PaymentRequestId__r.Contact__r.Id);
            metadata.put('accountId', txn.PaymentRequestId__r.Account__r.Id);
            metadata.put('transactionId', txn.Id);

            charge = stripeRest.charge(amount, currencyType, description, source, metadata);
        } catch (Stripe.RestException ex) {
            error = ex.errorResponse;
        }
        postProcessPayment(txn, paymentsService.getPaymentRequest(txn.PaymentRequestId__r.Id), error, charge);
    }

    private Long getAmount(Decimal amount) {
        String currencyType = UserInfo.getDefaultCurrency();
        System.debug('Current currency=' + currencyType+' amount='+amount);
        return Math.roundToLong((Stripe.zeroDecimalCurrencies.contains(currencyType)) ? amount : amount * 100);
    }

    private void preProcessError(List<PaymentRequest__c> paymentRequests) {
        for (PaymentRequest__c paymentRequest : paymentRequests) {
            paymentRequest.Status__c = 'payment_failed'; 
        }

        // update paymentRequests;
    }

    //TODO - migrate to municorn
    private void postProcessPayment(Transaction__c txn,
            PaymentRequest__c sourcePaymentRequest,
            Stripe.ErrorResponse errorResp,
            Stripe.Charge charge) {
        Boolean success = errorResp == null && charge.captured == true;
        txn.Status__c = charge.status != null ? charge.status : 'failed';
        txn.StripeChargeId__c = success ? charge.id : null;
        txn.StatusMessage__c = success ? 'Transaction successful' : errorResp.error.message;
        txn.AmountRefunded__c = charge.amount_refunded;
        txn.FailureCode__c = errorResp != null ? errorResp.error.code : charge.failure_code;
        txn.FailureMessage__c = errorResp != null ? errorResp.error.message : charge.failure_message;
        txn.TransactionDate__c = Datetime.now();
        txn.PaymentMethodType__c = errorResp == null ? charge.payment_method_details.type : null;
        txn.PaymentMethod__c = errorResp != null ? '-' : charge.payment_method;
        txn.PaymentCardLast4Digits__c = errorResp == null && charge.payment_method_details.type == 'card' ? charge.payment_method_details.card.last4 : null;
        txn.PaymentBankLast4Digits__c = errorResp == null && charge.payment_method_details.type == 'ach_debit' ? charge.payment_method_details.ach_debit.last4 : null;
        txn.PaymentBankName__c = errorResp == null && charge.payment_method_details.type == 'ach_debit' ? charge.payment_method_details.ach_debit.bank_name : null;
        /*
        SYS_IntegrationLog__c logResp = SYS_integrationLogHandler.getLogsToInsert(JSON.serialize(charge));
        logResp.SYS_IntegrationSettings__c = SYS_Constants.INT_TYPE;
        logResp.Type__c = 'INBOUND';
        logResp.SYS_Operation_Type__c = 'RESPONSE';
        logResp.Status__c = 'NEW';
        logResp.QB_Entity__c = 'Transaction__c';
        System.debug('transaction==log');
        insert logResp;*/

        PaymentRequest__c paymentRequest = [SELECT Id, Status__c, ItemNumber__c, Opportunity__r.Id FROM PaymentRequest__c WHERE Id = :sourcePaymentRequest.Id];
        paymentRequest.Status__c = success ? 'payment_done' : 'payment_failed';
        if (paymentRequest.ItemNumber__c == null) {
            paymentRequest.ItemNumber__c = 1;
        }
/*
        if (success) {
            Opportunity opp = [SELECT Id, StageName FROM Opportunity WHERE Id = :paymentRequest.Opportunity__r.Id];
            opp.StageName = 'Closed';
            // update opp;
        }
*/
        // insert txn;
        // update paymentRequest; 
    }

    public void subscribe(PaymentRequest__c paymentRequest) {
        Id contactId = paymentRequest.Contact__c;
        Double amount = paymentRequest.Amount__c;
        String interval = paymentRequest.Frequency__c;
        Stripe.Customer cus = getCustomer(contactId);

        try {
            Stripe.Product product = stripeRest.createProduct('defaultProduct');
            Stripe.Plan plan = stripeRest.createPlan(getAmount(amount), UserInfo.getDefaultCurrency(), interval, product.name);

            Stripe.Subscription subscription = stripeRest.createSubscription(plan.id, cus.id, paymentRequest);
            paymentRequest.SubscriptionId__c = subscription.id;
        } catch (Stripe.RestException ex) {
            Stripe.Error error = ex.errorResponse.error;
            paymentRequest.Status__c = 'payment_failed';
            paymentRequest.Status_Message__c = error.message;
        } finally {
            update paymentRequest;
        }
    }

    private Stripe.Customer getCustomer(Id contactId) {
        String stripeCustomerId = [SELECT StripeCustomerId__c FROM Contact WHERE Id = :contactId].StripeCustomerId__c;

        Stripe.Customer cus = new Stripe.Customer();
        if (stripeCustomerId != null) {
            cus = stripeRest.getCustomer(stripeCustomerId);
        } else {
            cus = stripeRest.createCustomer();
            System.debug('Created new customer for account/contact=' + contactId + ' with stripe customer id=' + cus.id);
        }
        return cus;
    }

    private void updateStripeCustomerId(Id contactId, String stripeCustomerId) {
        Contact contact = [SELECT Id, StripeCustomerId__c FROM Contact WHERE Id = :contactId];
        if (contact.StripeCustomerId__c == null) {
            contact.StripeCustomerId__c = stripeCustomerId;
            update contact;
        }
    }

    private Stripe.Card registerCard(String stripeToken, String stripeCustomerId) {
        Stripe.Card card = stripeRest.createCard(stripeCustomerId, stripeToken);
        System.debug('Created new card for customer=' + stripeCustomerId + ' with stripe card id=' + card.id);

        stripeRest.setDefaultPaymentSource(stripeCustomerId, card.id);
        return card;
    }

    private void setDefaultSource(List<Stripe.Card> cards, Stripe.Customer cus) {
        String default_source = cus.default_source;
        System.debug('default_source=' + default_source);
        for (Stripe.Card card : cards) {
            if (card.id == default_source) {
                card.default_source = true;
            }
        }
    }
    public static String escape(String stripeResponse) {
        return stripeResponse.replace('"currency":', '"currency_x":').replace('"object":', '"object_x":');
    }
}