force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>Activity-{0}</displayFormat>
        <label>Activity#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Activity</relationshipLabel>
    <relationshipName>Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Undelivered</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>sms</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Activity__c/fields/When__c.field-meta.xml
<CustomField>
    <fullName>When__c</fullName>
    <label>When</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Request_Group__c/Payment_Request_Group__c.object-meta.xml
<CustomObject>
    <description>This is a payment request group for multiple payment requests to be added to cart</description>
    <label>Payment Requests</label>
    <nameField>
        <label>Payment Request Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request_Group__c/fields/uuid__c.field-meta.xml
<CustomField>
    <fullName>uuid__c</fullName>
    <label>uuid</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/PaymentRequest__c.object-meta.xml
<CustomObject>
    <description>This is a payment request made by a user</description>
    <label>Payment Request</label>
    <nameField>
        <label>Payment Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentRequest__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount for which the payment request is being made</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/PaymentRequests__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequests__c</fullName>
    <label>Payment Requests</label>
    <referenceTo>Payment_Request_Group__c</referenceTo>
    <relationshipName>PaymentRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>payment_new</fullName>
            </value>
            <value>
                <fullName>payment_done</fullName>
            </value>
            <value>
                <fullName>payment_expired</fullName>
            </value>
            <value>
                <fullName>payment_failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data0__c.field-meta.xml
<CustomField>
    <fullName>data0__c</fullName>
    <label>data0</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/How_to_process__c.field-meta.xml
<CustomField>
    <fullName>How_to_process__c</fullName>
    <label>How to process?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>use_object_setting</fullName>
                <default>true</default>
                <label>Use Object Setting</label>
            </value>
            <value>
                <fullName>use_custom_apex_handler</fullName>
                <label>Use Custom Apex Handler</label>
            </value>
            <value>
                <fullName>ignore_log</fullName>
                <label>Ignore Log</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;NEW&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>CALLOUT ERROR</label>
            </value>
            <value>
                <fullName>PENDING_PARENT</fullName>
                <label>PENDING PARENT</label>
            </value>
            <value>
                <fullName>READY_FOR_PROCESSING</fullName>
                <label>READY FOR PROCESSING</label>
            </value>
            <value>
                <fullName>ENQUEUED_FOR_RETRY</fullName>
                <label>ENQUEUED FOR RETRY</label>
            </value>
            <value>
                <fullName>READY_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>READY_FOR_PARENT</label>
            </value>
            <value>
                <fullName>WAITING_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>WAITING_FOR_PARENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>This field is used when the JSON has more than 1M characters and needs to spread over multiple records.</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PMA_ContactTriggerHandler.cls
public class PMA_ContactTriggerHandler {
    public static void handleTrigger(List < Contact > contactList, System.TriggerOperation triggerEvent) {
        switch on triggerEvent {
            when BEFORE_INSERT {
                updateContactUUID(contactList);
            }

            when AFTER_INSERT { //AFTER_INSERT, AFTER_UPDATE
                addSMSActivityPaymentRequest(contactList);
            }
        }
    }
    public Static void updateContactUUID(List < Contact > contactList) {
        for (Contact g: contactList) {
            g.UUID__c = PMA_ExternalSiteFormsUtility.getUUID();
        }
    }
    Public Static Void addSMSActivityPaymentRequest(List < Contact > contactList) {
        PaymentsService paymentsService = new PaymentsService();
        List < Activity__c > activityList = new List < Activity__c > ();
        SYS_IntegrationLog__c errorLog = new SYS_IntegrationLog__c();

        //String activity_UUID;
        String guestPageUrl = 'StripePaymentPage?reqid=';
        //Payment Request Init
        Date firstChargeDate = System.TODAY();
        String frequency = 'single';
        String paymentType = 'immediate';
        String paymentRequestGroupId = PMA_ExternalSiteFormsUtility.getUUID();
        Double amount = 2.0;
        Integer itemNumber = 1;
        //activity_UUID = PMA_ExternalSiteFormsUtility.getUUID();
        for (Contact g: contactList) {

            Id accountId = g.AccountId;
            Id contactId = g.Id;
            Id opportunityId = null;
            String email = g.Email;
            String paymentName = 'Request ' + g.FirstName + ' ' + g.LastName + ' For $2';
            if (g.Phone_Number__c != '' && contactId != '') {
                PaymentRequest__c payreq = paymentsService.createNewPaymentRequest(paymentName, contactId, accountId, opportunityId, paymentType, amount, email, frequency, firstChargeDate, itemNumber, paymentRequestGroupId);
                if (payreq.Id != '') {
                    Activity__c activity = new Activity__c();
                    activity.Customer__c = g.Id;
                    //activity.UUID__c = activity_UUID;
                    activity.Type__c = 'sms';
                    activity.Email__c = g.Email;
                    activity.Status__c = 'Queued';
                    activity.Subject__c = 'Outbound SMS to ' + g.LastName + ' - ' + g.Phone_Number__c + ' For PMA Agreement';
                    activity.When__c = System.now();
                    activity.Phone__c = PMA_ExternalSiteFormsUtility.formatPhone(g.Phone_Number__c);
                    activity.Message__c = 'Please Pay $' + payreq.Amount__c + ' to Start PMA Membership ' + PMA_ExternalSiteFormsUtility.getGuestSiteUrl(guestPageUrl) + '' + payreq.PaymentRequests__r.uuid__c;
                    activityList.add(activity);
                }
            }
        }
        if (activityList.size() > 0) {
            try {
                insert activityList;
            } catch (Exception e) {
                System.debug('Error in Storing Contact: ' + e.getMessage());
                //Generate a Log record
                errorLog.data0__c = 'Exception Type: ' + e.getTypeName() + ' Exception Message: ' + e.getMessage();
                // errorLog = SYS_integrationLogHandler.getLogsToInsert( error_message.toString() );
                errorLog.Type__c = 'OUTBOUND';
                errorLog.Status__c = 'ERROR';
                errorLog.How_To_Process__c = 'ignore_log';
            }
            if (errorLog != new SYS_IntegrationLog__c()) {
                insert errorLog;
            }
        }

    }

}