force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>Activity-{0}</displayFormat>
        <label>Activity#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Activity</relationshipLabel>
    <relationshipName>Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Undelivered</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Trackable__c.field-meta.xml
<CustomField>
    <fullName>Trackable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trackable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>sms</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Activity__c/fields/When__c.field-meta.xml
<CustomField>
    <fullName>When__c</fullName>
    <label>When</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SYS_Tracker__c/SYS_Tracker__c.object-meta.xml
<CustomObject>
    <label>SYS_Tracker</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>SYS_Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_Tracker__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UUID</fullName>
            </value>
            <value>
                <fullName>Display Pic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_Tracker__c/fields/Valid_till__c.field-meta.xml
<CustomField>
    <fullName>Valid_till__c</fullName>
    <label>Valid till</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SYS_Tracker__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <externalId>true</externalId>
    <label>WhatId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_Tracker__c/fields/WhoId__c.field-meta.xml
<CustomField>
    <fullName>WhoId__c</fullName>
    <label>WhoId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomActivityService.cls
public class CustomActivityService {
    public static Activity__c getActivityByUUID(String uuid){
        return [SELECT Id,Name,
            Customer__c,
            Customer__r.Name,
            Customer__r.Phone_Number__c,
            Customer__r.Email,
            Phone__c,Message__c,Email__c,Type__c,UUID__c,When__c,
            Log__c,Status__c,Subject__c,Trackable__c,CreatedDate,LastModifiedDate,OwnerId FROM Activity__c WHERE UUID__c =:uuid ];
    }

    public static Activity__c getActivityIntent(Id id) {
        return [SELECT Id,Name,
                Customer__c,
                Customer__r.Name,
                Customer__r.Phone_Number__c,
                Customer__r.Email,
                Phone__c,Message__c,Email__c,Type__c,UUID__c,When__c,
                Log__c,Status__c,Subject__c,Trackable__c,CreatedDate,LastModifiedDate,OwnerId FROM Activity__c WHERE Id = :id];
    }

    public static Activity__c createNewSmsActivity(
            //String paymentName,
            Id contactId,
            String toPhone,
            String email,
            String subject,
            String messageBody) {
        System.debug('Custom Activity service, create new Sms Activity for' +
                ', contact id=' + contactId +
                ', To Phone=' + toPhone +
                ', email=' + email +
                ', Subject =' + subject +
                ', Message Body =' + messageBody);

                Activity__c smsActivity = new Activity__c(
                Customer__c = contactId,
                Type__c = 'sms',
                Email__c = email,
                Status__c = 'Queued',
                When__c = System.now(),
                Phone__c = toPhone,
                Subject__c = subject,
                Message__c = messageBody
        );

        insert smsActivity;

        SYS_Tracker__c sysTracker = new SYS_Tracker__c();
        sysTracker.Type__c = 'Activity SMS';
        sysTracker.WhatId__c = contactId;
        sysTracker.WhoId__c = smsActivity.Id;
        //sysTracker.Valid_till__c = Now() + 865; 
        insert sysTracker;

        return getActivityIntent(smsActivity.Id);
    }

}