force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>Activity-{0}</displayFormat>
        <label>Activity#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Payment_Intent__c.field-meta.xml
<CustomField>
    <fullName>Payment_Intent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Intent</label>
    <referenceTo>Payment_Intent__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Undelivered</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>sms</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>PMA Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMA Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PMA Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>Order_Item__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Vendor Not Found ..</errorMessage>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PMA Orders</relationshipLabel>
    <relationshipName>PMA_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/Payment_Gateway__c.object-meta.xml
<CustomObject>
    <label>Payment Gateway</label>
    <nameField>
        <label>Payment Gatway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Gateway__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Gateway_Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Public_Key__c</fullName>
    <label>Gateway Public Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/Payment_Intent__c.object-meta.xml
<CustomObject>
    <label>Payment Intent</label>
    <nameField>
        <label>Payment Intent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Intents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Intent__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Intents</relationshipLabel>
    <relationshipName>Payment_Intents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Payment Intents</relationshipLabel>
    <relationshipName>Payment_Intents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Gateway</label>
    <referenceTo>Payment_Gateway__c</referenceTo>
    <relationshipLabel>Payment Intents</relationshipLabel>
    <relationshipName>Payment_Intents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Payment_Link__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link__c</fullName>
    <formula>IF( NOT(ISBLANK(UUID__c )) , 
    ( $Label.GuestUserPaymentLink  +  UUID__c) , &quot;&quot;)</formula>
    <label>Payment Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>payment_new</fullName>
            </value>
            <value>
                <fullName>payment_done</fullName>
            </value>
            <value>
                <fullName>payment_expired</fullName>
            </value>
            <value>
                <fullName>payment_failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>PMA Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMA Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PMA Products</relationshipLabel>
    <relationshipName>PMA_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data0__c.field-meta.xml
<CustomField>
    <fullName>data0__c</fullName>
    <label>data0</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;NEW&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>CALLOUT ERROR</label>
            </value>
            <value>
                <fullName>PENDING_PARENT</fullName>
                <label>PENDING PARENT</label>
            </value>
            <value>
                <fullName>READY_FOR_PROCESSING</fullName>
                <label>READY FOR PROCESSING</label>
            </value>
            <value>
                <fullName>ENQUEUED_FOR_RETRY</fullName>
                <label>ENQUEUED FOR RETRY</label>
            </value>
            <value>
                <fullName>READY_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>READY_FOR_PARENT</label>
            </value>
            <value>
                <fullName>WAITING_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>WAITING_FOR_PARENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>This field is used when the JSON has more than 1M characters and needs to spread over multiple records.</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PMA_ContactInvocableHandler.cls
global class PMA_ContactInvocableHandler {
    global class MyInvocableVariable {
        @InvocableVariable(label='Contact Id' required=true)  
        global Id recId;
    
        @InvocableVariable(label='Contact Old Value' required=true)  
        global Contact oldVal;
    
        @InvocableVariable(label='Contact Current Value' required=true)
        global Contact newVal;

        @InvocableVariable(label='Order Id' required=true)  
        global Id orderId;

        @InvocableVariable(label= 'Contact Operation Type' required = true)
        global String operationType;
    }
    @InvocableMethod(label='Capture Contact Change' description='To Create Order and Payment Intent Record and Activity')
    global static void captureContactChangeRequest(List<MyInvocableVariable> myInvocableVariableList) {
        List<Contact> newList = new List<Contact>();
        List<Contact> oldList = new List<Contact>();
        Id orderId;
        
        List<SYS_IntegrationLog__c> insertSysLog = new List<SYS_IntegrationLog__c>();

        String operationType = myInvocableVariableList.size() > 0 ? myInvocableVariableList[0].operationType.toUppercase() : 'CREATE';


        for(MyInvocableVariable itr:myInvocableVariableList){
            newList.add(itr.newVal);   
            oldList.add(itr.oldVal);   
            orderId = itr.orderId;
        } 
        /* for (Contact g: newList) {
            g.UUID__c = SYS_Helper.getUUID();
        } */
        Payment_Gateway__c pmasandBox = new Payment_Gateway__c();
        List < Activity__c > activityList = new List < Activity__c > ();
        SYS_IntegrationLog__c errorLog = new SYS_IntegrationLog__c();
        Order__c order = new Order__c();
        order = [SELECT Id,Name,Account__c,Order_Type__c,Status__c,Vendor__c,Total_Price__c,UUID__c,CreatedDate,LastModifiedDate,OwnerId,
                (SELECT Id,Name,Line_Total_Price__c,List_Price__c,Order__c,Product__c,Quantity__c,Total_Price__c,CreatedDate,LastModifiedDate FROM Order_Items__r)
                FROM Order__c
                WHERE Id = :orderId AND (Order_Type__c = 'Registration') AND (Status__c = 'Active' )];
        pmasandBox = [SELECT Access_Token__c,CreatedDate,Gateway_Public_Key__c,Id,LastModifiedDate,Name,OwnerId,Test_Mode__c FROM Payment_Gateway__c LIMIT 1];
        //Payment Intent Init
        Date firstChargeDate = System.TODAY();
        String frequency = 'single';
        String paymentType = 'immediate';
        for (Contact g: newList) {
            Id accountId = g.AccountId;
            Id contactId = g.Id;
            Id opportunityId = null;
            Double amount = order.Total_Price__c;
            //String fromPhone = PMA_ExternalSiteFormsUtility.formatPhone(g.Plivo_Sender_Id__c);
            String toPhone = PMA_ExternalSiteFormsUtility.formatPhone(g.Phone_Number__c);
            String email = g.Email;
            String paymentName = 'Payment for Membership Fees by ' + g.FirstName + ' ' + g.LastName;
            Id paymentGatewayId = pmasandBox.Id;
            Payment_Intent__c payreq = PaymentIntentService.createNewPaymentIntent(paymentName , paymentGatewayId , contactId, accountId, opportunityId, orderId, paymentType, amount, email, frequency, firstChargeDate);
            if (payreq.Id != null) {
                String subject = 'Outbound SMS to ' + g.LastName + ' - ' + toPhone + ' for PMA MemberShip Purchase';
                String messageBody = 'Please Pay $' + payreq.Amount__c + ' to Start PMA Membership ' + payreq.Payment_Link__c;
                Activity__c activityCreate = CustomActivityService.createNewSmsActivity(contactId, toPhone, email, subject, messageBody);
                
            } else{
                //TODO write handler if failure
                System.debug('DML Error in Creation of Payment Intent: ');
                //Generate a Log record
                errorLog.data0__c = 'Exception Type: DML Error Exception Message: Error in Creation of Payment Intent';
                errorLog.Type__c = 'RESPONSE';
                errorLog.Status__c = 'ERROR';
                errorLog.How_To_Process__c = 'ignore_log';
            }
        }
        if (errorLog != new SYS_IntegrationLog__c()) {
            insert errorLog;
        }
    }
}