force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>Activity-{0}</displayFormat>
        <label>Activity#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Athrz_SendEmailInvocableHandler.cls
global class Athrz_SendEmailInvocableHandler {
    public Athrz_SendEmailInvocableHandler() {

    }

    @InvocableMethod(label='Send email to customer')
    global static void sendEmailToCustomer(List<Activity__c> newList) {
        Set<String> intentList = new List<String>();
        
        try {
            for(Activity__c activity : newList) {
                System.debug('uuid '+activity.UUID__c);
                activity.Message__c	= Athrz_utility.sendEmail(activity.UUID__c).success ? 
                                    'Email successfully sent' : 'Failed to send email';

            }
            update newList;

        } catch(Exception e) {
            System.debug(e.getStackTraceString());
        }
    }
}