force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK(  Birthdate ) ) ,
 ( YEAR(TODAY()) - YEAR(Birthdate) -
IF(
       OR (
                  MONTH(TODAY()) &lt; MONTH(Birthdate),
                  AND(
                      MONTH(TODAY()) == MONTH(Birthdate),
                      DAY(TODAY()) &lt; DAY(Birthdate)
                    )
        ),
        1,
        0
)),
 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Default_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Default_Payment_Method__c</fullName>
    <inlineHelpText>Default Card or Bank Token</inlineHelpText>
    <label>Default Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Non-Binary</fullName>
                <isActive>false</isActive>
                <label>Non-Binary</label>
            </value>
            <value>
                <fullName>Prefer Not To Say</fullName>
                <isActive>false</isActive>
                <label>Prefer Not To Say</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Payment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date_Time__c</fullName>
    <label>Payment Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Payment_SMS_Sent__c.field-meta.xml
<CustomField>
    <fullName>Payment_SMS_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment SMS Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Sponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No Vendors Found</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <infoMessage>Search for Referred by Vendor</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Sponsors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomerId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

force-app/main/default/classes/SearchController.cls
public with sharing class SearchController {

    @AuraEnabled
    public static List<Contact> getOpenTabMembers(){
        List < Contact > membersList = new List< Contact >();
        RecordType memberRecordType = [SELECT Id,DeveloperName FROM RecordType WHERE DeveloperName = 'Member'];
        String memberRecordTypeId = (memberRecordType!=null) ? memberRecordType.Id : '' ;
        System.debug('test memberRecordTypeId'+ memberRecordTypeId);
        if(memberRecordTypeId!=''){
            membersList = [SELECT Id, Name, LastName, FirstName, Gender__c, Age__c, Birthdate, Phone_Number__c, Email,
                AccountId, Sponsor__c, StripeCustomerId__c, Active__c, Default_Payment_Method__c, Description, Fax,
                MailingAddress, MailingCity, MailingCountry, MailingPostalCode, MailingState, MailingStreet, Salutation, Title,
                Payment_Date_Time__c, Payment_SMS_Sent__c, RecordTypeId, LastModifiedDate, CreatedDate, OwnerId FROM Contact WHERE (RecordTypeId =: memberRecordTypeId) AND (Active__c = TRUE) ];
                System.debug('test membersList'+ membersList);
            return membersList;     
        }

        return membersList;
    }
    @AuraEnabled
    public static List<Contact> searchActiveMembers(String keyword){
        List < Contact > membersList = new List< Contact >();
        RecordType memberRecordType = [SELECT Id,DeveloperName FROM RecordType WHERE DeveloperName = 'Member'];
        String memberRecordTypeId = (memberRecordType!=null) ? memberRecordType.Id : '' ;
        System.debug('searched memberRecordTypeId'+ memberRecordTypeId);
        if(memberRecordTypeId!='' && keyword !=''){
            string tempkeyword= '%' + keyword + '%';
            membersList = [SELECT Id, Name, LastName, FirstName, Gender__c, Age__c, Birthdate, Phone_Number__c, Email,
                AccountId, Sponsor__c, StripeCustomerId__c, Active__c, Default_Payment_Method__c, Description, Fax,
                MailingAddress, MailingCity, MailingCountry, MailingPostalCode, MailingState, MailingStreet, Salutation, Title,
                Payment_Date_Time__c, Payment_SMS_Sent__c, RecordTypeId, LastModifiedDate, CreatedDate, OwnerId FROM Contact WHERE (RecordTypeId =: memberRecordTypeId) AND (Active__c = TRUE) AND (Phone_Number__c LIKE : tempkeyword ) ];
                System.debug('searched keyword'+ keyword);
                System.debug('searched membersList'+ membersList);
        }
        return membersList; 
    }
    @AuraEnabled(Cacheable = true)
    public static List<SObject> search(
            String objectType,
            Map<String, Object> filterParams,
            String searchText,
            String[] selectFields,
            String searchOnField,
            Integer numRecords) {
        String limitClause = numRecords == null || numRecords <= 0 ? ' LIMIT 20' : ' LIMIT ' + numRecords;

        String whereClause = '';
        for (String filter : filterParams.keySet()) {
            whereClause += '(' + filter + getQueryParamValue(filterParams.get(filter)) + ') AND ';
        }
        whereClause += searchOnField + ' LIKE \'%' + searchText.toLowerCase() + '%\'';

        String query = 'SELECT ' + String.join(selectFields, ',') + ' FROM ' + objectType +
                ' WHERE ' + whereClause + ' ORDER BY ' + searchOnField + ' ' + limitClause;
        System.debug('Search query=' + query);

        return Database.query(query);
    }

    private static String getQueryParamValue(Object paramValue) {
        if (paramValue instanceof Integer ||
                paramValue instanceof Long ||
                paramValue instanceof Double ||
                paramValue instanceof Decimal) {
            return String.valueOf(paramValue);
        }
        return '\'' + paramValue + '\'';
    }
}