force-app/main/default/objects/Contact/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomerId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HttpHeaders__mdt/HttpHeaders__mdt.object-meta.xml
<CustomObject>
    <label>HTTP Header</label>
    <pluralLabel>HTTP Headers</pluralLabel>
</CustomObject>

force-app/main/default/objects/HttpHeaders__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/IntegrationSetting__mdt.object-meta.xml
<CustomObject>
    <label>Integration Setting</label>
    <pluralLabel>Integration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationSetting__mdt/fields/BaseAPIEndPoint__c.field-meta.xml
<CustomField>
    <fullName>BaseAPIEndPoint__c</fullName>
    <label>Base API End Point</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/fields/Flat_Key_for_Resource__c.field-meta.xml
<CustomField>
    <fullName>Flat_Key_for_Resource__c</fullName>
    <label>Flat Key for Resource</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/fields/UpdateMethod__c.field-meta.xml
<CustomField>
    <fullName>UpdateMethod__c</fullName>
    <defaultValue>&apos;POST&apos;</defaultValue>
    <label>Update Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Custom_Apex_Handler__c.field-meta.xml
<CustomField>
    <fullName>Custom_Apex_Handler__c</fullName>
    <label>Custom Apex Handler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data0__c.field-meta.xml
<CustomField>
    <fullName>data0__c</fullName>
    <label>data0</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data1__c.field-meta.xml
<CustomField>
    <fullName>data1__c</fullName>
    <label>data1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data2__c.field-meta.xml
<CustomField>
    <fullName>data2__c</fullName>
    <label>data2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data3__c.field-meta.xml
<CustomField>
    <fullName>data3__c</fullName>
    <label>data3</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data4__c.field-meta.xml
<CustomField>
    <fullName>data4__c</fullName>
    <label>data4</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data5__c.field-meta.xml
<CustomField>
    <fullName>data5__c</fullName>
    <label>data5</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data6__c.field-meta.xml
<CustomField>
    <fullName>data6__c</fullName>
    <label>data6</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data7__c.field-meta.xml
<CustomField>
    <fullName>data7__c</fullName>
    <label>data7</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data8__c.field-meta.xml
<CustomField>
    <fullName>data8__c</fullName>
    <label>data8</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data9__c.field-meta.xml
<CustomField>
    <fullName>data9__c</fullName>
    <label>data9</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Flat_Key_for_Resource__c.field-meta.xml
<CustomField>
    <fullName>Flat_Key_for_Resource__c</fullName>
    <description>Defines the flat key in incoming JSON that will be used to identify the Resource and hence the object setting</description>
    <label>Flat Key for Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/How_to_process__c.field-meta.xml
<CustomField>
    <fullName>How_to_process__c</fullName>
    <label>How to process?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>use_object_setting</fullName>
                <default>true</default>
                <label>Use Object Setting</label>
            </value>
            <value>
                <fullName>use_custom_apex_handler</fullName>
                <label>Use Custom Apex Handler</label>
            </value>
            <value>
                <fullName>ignore_log</fullName>
                <label>Ignore Log</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;NEW&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>CALLOUT ERROR</label>
            </value>
            <value>
                <fullName>PENDING_PARENT</fullName>
                <label>PENDING PARENT</label>
            </value>
            <value>
                <fullName>READY_FOR_PROCESSING</fullName>
                <label>READY FOR PROCESSING</label>
            </value>
            <value>
                <fullName>ENQUEUED_FOR_RETRY</fullName>
                <label>ENQUEUED FOR RETRY</label>
            </value>
            <value>
                <fullName>READY_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>READY_FOR_PARENT</label>
            </value>
            <value>
                <fullName>WAITING_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>WAITING_FOR_PARENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_Http_Status__c.field-meta.xml
<CustomField>
    <fullName>SYS_Http_Status__c</fullName>
    <label>Http Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_IntegrationSettings__c.field-meta.xml
<CustomField>
    <fullName>SYS_IntegrationSettings__c</fullName>
    <label>SYS_IntegrationSettings</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quickbooks</fullName>
            </value>
            <value>
                <fullName>JIRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>SYS_Operation_Type__c</fullName>
    <label>Operation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MERGE</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>UPSERT</fullName>
            </value>
            <value>
                <fullName>INSERT</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
            <value>
                <fullName>CDC</fullName>
                <isActive>false</isActive>
                <label>CDC</label>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
                <isActive>false</isActive>
                <label>RESPONSE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_RequestId__c.field-meta.xml
<CustomField>
    <fullName>SYS_RequestId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RequestId</label>
    <referenceTo>SYS_IntegrationLog__c</referenceTo>
    <relationshipLabel>Callout Response Logs</relationshipLabel>
    <relationshipName>RequestId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/St_Customer_Out_SYS_ApplicationService.cls
public with sharing class St_Customer_Out_SYS_ApplicationService  extends SYS_ApplicationService {
    public St_Customer_Out_SYS_ApplicationService() {

    }
    //Generate Request params from JSON for Outbound
    public override String sanitizeJSONForOutbound(String jsonRecord) {
        String finalJSON = jsonRecord.replace('\n', ' ');
        String newrequestParams=''; 
        Map < String, Object > jsonobj = (Map < String, Object > ) JSON.deserializeUntyped(finalJSON);
        List < String > reqkeymap = new List < String > (jsonobj.keySet());
        reqkeymap.sort();
        Integer i=0;
        for (String key: reqkeymap) {
            if (!String.isBlank(key) && jsonobj.get(key) != '' && (jsonobj.get(key)) instanceOf String)
            if(i==0){
                newrequestParams += '?' + key.toLowerCase() + '=' + jsonobj.get(key);
            } else {
                newrequestParams += '&' + key.toLowerCase() + '=' + jsonobj.get(key);
            }
            i++;
        }
        finalJSON = newrequestParams;
        System.debug('newrequestParams: ' + newrequestParams);
        return finalJSON;
    }

    //TO DO a Callout if customer is not created - pending 
    public override HttpRequest buildOutboundHttpRequest(SYS_IntegrationLog__c log){
        HttpRequest req = new HttpRequest();
        IntegrationSetting__mdt integrationSetting = SYS_DataCache.integrationSetting.get(SYS_Datacache.INT_TYPE);
        String baseEndpoint = integrationSetting.BaseAPIEndPoint__c;

        List<HttpHeaders__mdt> httpHeader = SYS_DataCache.headerSetting;
        req.setMethod(integrationSetting.UpdateMethod__c);
        for(HttpHeaders__mdt head:httpHeader){
            SYS_debug.log('header is = '+head.MasterLabel + ''+head.Value__c);
            req.setHeader(String.valueOf(head.MasterLabel), String.valueOf(head.Value__c));
        }
        Boolean createCustomer = true;
        String resourceUrl = integrationSetting.BaseAPIEndPoint__c+SYS_DataCache.objectSettingMap.get(SYS_DataCache.OBJ_TYPE).ResourcePath__c;
        List<Contact> rec = [SELECT StripeCustomerId__c FROM Contact WHERE Id = :log.WhatId__c LIMIT 1];
        if( rec.size() >0 ){
            resourceUrl = resourceUrl +'/'+rec[0].StripeCustomerId__c;
            createCustomer = false;
        }
        req.setEndpoint(resourceUrl);
        if(createCustomer){
          //  HttpResponse createResponse = http.send(req);
            //Log Customer Create JSON into Syslog
          //  SYS_IntegrationLog__c createsyslog = generatelogForOutboundResult(createResponse,log);
        }
        return req;
    }

    /* ------------------------------------------------------------------------ */
    // To do midify outbound creteria based on insert and update
    public override HttpResponse doOutbound(SYS_IntegrationLog__c log){

        Http http = new Http();
        HttpRequest req = buildOutboundHttpRequest(log);
        
        String body = log.data0__c != null ? log.data0__c : '' +
                            log.data1__c != null ? log.data1__c : '' +
                            log.data2__c != null ? log.data2__c : '' +
                            log.data3__c != null ? log.data3__c : '' +
                            log.data4__c != null ? log.data4__c : '' +
                            log.data5__c != null ? log.data5__c : '' +
                            log.data6__c != null ? log.data6__c : '' +
                            log.data7__c != null ? log.data7__c : '' + 
                            log.data8__c != null ? log.data8__c : '' +
                            log.data9__c != null ? log.data9__c : '' ; 
        
        //Log Customer Create JSON into Syslog
       // SYS_IntegrationLog__c createsyslog = generatelogForOutboundResult(createResponse,log);
        //Build Customer Update Request
        body = preprocessJSONForOutbound(log,body);
        req.setBody(body);
        SYS_debug.log('body:'+body);
        HttpResponse response = http.send(req);

        return response;
        
    }
    //Add Immediate Outbound Response Syslog to Upsert Using Custom Apex Handler
    // Added Custom Apex handler and resource path identifier
    public override SYS_IntegrationLog__c generatelogForOutboundResult(HttpResponse resp,SYS_IntegrationLog__c log){
        SYS_IntegrationLog__c logResp = getLogsToInsert(resp.getBody());
        //Added Status 202 - Accepted in Creteria
        if(resp.getStatusCode() != 202 && resp.getStatusCode() != 201 && resp.getStatusCode() != 200){
            SYS_debug.log('#### resp status: '+resp.getStatus());
            SYS_debug.log('#### resp code: '+resp.getStatusCode()); 
            SYS_debug.log('#### resp: '+resp.getBody());

            
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.Status__c.isCreateable()) {
                logResp.Status__c = 'ERROR';
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Http_Status__c.isCreateable()) {
                logresp.SYS_Http_Status__c = integer.valueOf(resp.getStatusCode());
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_RequestId__c.isCreateable()) {
                logResp.SYS_RequestId__c = log.Id;
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.WhatId__c.isCreateable()) {
                logResp.WhatId__c = log.WhatId__c;
            }
            
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.Type__c.isCreateable()) {
                logResp.Type__c = 'INBOUND';
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Operation_Type__c.isCreateable()) {
                logResp.SYS_Operation_Type__c = 'RESPONSE';
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.How_To_Process__c.isCreateable()) {
                logResp.How_To_Process__c = 'ignore_log';
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Operation_Type__c.isCreateable()) {
                logResp.SYS_IntegrationSettings__c = SYS_DataCache.INT_TYPE;
            }
        }
        else{

            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.Status__c.isCreateable()) {
                logResp.Status__c = 'DONE';
            }
            
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Http_Status__c.isCreateable()) {
                logresp.SYS_Http_Status__c = Integer.valueOf(resp.getStatusCode());
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_RequestId__c.isCreateable()) {
                logResp.SYS_RequestId__c = log.Id;
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.WhatId__c.isCreateable()) {
                logResp.WhatId__c = log.WhatId__c;
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.Type__c.isCreateable()) {
                logResp.Type__c = 'INBOUND';
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Operation_Type__c.isCreateable()) {
                logResp.SYS_IntegrationSettings__c = SYS_DataCache.INT_TYPE;
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.Flat_Key_for_Resource__c.isCreateable()) {
                logResp.Flat_Key_for_Resource__c = 'object';
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.How_To_Process__c.isCreateable()) {
                log.How_to_process__c = 'use_custom_apex_handler';
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.Custom_Apex_Handler__c.isCreateable()) {
                log.Custom_Apex_Handler__c = 'St_Customer_Out_SYS_ApplicationService';
            }
            if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Operation_Type__c.isCreateable()) {
                logResp.SYS_Operation_Type__c = 'UPSERT';
            }
        }

        return logResp;
    }
    // For Outbound. Called from doInbound() in ApplicationService
    //Upsert Immediate Response using WhattID
    public override List<sObject> transformJsonToSObject(String jsonBody,String resource) {
        List < sObject > sObjectsToDML = SYS_Transformer.getSObjectsToUpsert(new List<String>{jsonBody},resource);
        SYS_IntegrationLog__c log = SYS_DataCache.log;
        String recordId = log.WhatId__c;
        if (sObjectsToDML.size() > 0) {
            for (sObject currentObj: sObjectsToDML) {
                if (currentObj instanceOf Contact) {
                    currentObj.put('Id' , recordId);
                }
            }
        }
        return sObjectsToDML;
    }
    
}