force-app/main/default/objects/Contact/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomerId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/Payment_Gateway__c.object-meta.xml
<CustomObject>
    <label>Payment Gateway</label>
    <nameField>
        <label>Payment Gatway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Gateway__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Gateway_Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Public_Key__c</fullName>
    <label>Gateway Public Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/Payment_Intent__c.object-meta.xml
<CustomObject>
    <label>Payment Intent</label>
    <nameField>
        <label>Payment Intent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Intents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Intent__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Intents</relationshipLabel>
    <relationshipName>Payment_Intents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Gateway</label>
    <referenceTo>Payment_Gateway__c</referenceTo>
    <relationshipLabel>Payment Intents</relationshipLabel>
    <relationshipName>Payment_Intents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Intent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>payment_new</fullName>
            </value>
            <value>
                <fullName>payment_done</fullName>
            </value>
            <value>
                <fullName>payment_expired</fullName>
            </value>
            <value>
                <fullName>payment_failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Gateway</label>
    <referenceTo>Payment_Gateway__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payment_Intent__c.field-meta.xml
<CustomField>
    <fullName>Payment_Intent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Intent</label>
    <referenceTo>Payment_Intent__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>initiated</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>succeeded</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>failed</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/StripeChargeId__c.field-meta.xml
<CustomField>
    <fullName>StripeChargeId__c</fullName>
    <description>Stripe charge id</description>
    <externalId>true</externalId>
    <label>StripeChargeId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/Charge.recordType-meta.xml
<RecordType>
    <fullName>Charge</fullName>
    <active>true</active>
    <description>For Authorizations, Charges and Refunds.</description>
    <label>Charge</label>
</RecordType>

force-app/main/default/classes/TransactionController.cls
public without sharing class TransactionController {
    private static StripeService stripeService = new StripeService();
    private static CustomLabelsService customLabelsService = new CustomLabelsService();
	private static TransactionService txnService = new TransactionService();
    
    public List<Stripe.Card> cards { get; set; }

    public String organization { get; set; }

    public String stripePaymentRequestJson { get; set; }
    public String error { get; set; }
    public String stripePublishableKey { get; set; }
    public Boolean appMode { get; set; }

    public String labelsJson { get; set; }
    public Map<String, Object> labels { get; set; }
    public Payment_Gateway__c stripePaymentGateway { get; set; }
    public List<Payment_Intent__c> paymentRequests { get; set; }
    public Payment_Intent__c paymentIntent { get; set; }
    public Stripe.Payments payments { get; set; }
    public Stripe.Payments paymentReceipt { get; set; }
    public Contact contact { get; set; }

    public TransactionController() {
        //Get Payment Request Details
        paymentRequests = PaymentIntentService.getPaymentRequestByUUID(ApexPages.currentPage().getParameters().get('reqid'));
        System.debug('test paymentRequests '+paymentRequests);
        assert(!paymentRequests.isEmpty(), 'No payment requests found');
        if(!paymentRequests.isEmpty()){
            paymentIntent = paymentRequests[0];
            contact = [SELECT Id, Name, StripeCustomerId__c FROM Contact WHERE Id = :paymentIntent.Contact__r.Id];
            System.debug('test contact '+contact);
            if(paymentIntent.Status__c == 'payment_expired') {
                assert(false, 'Payment Request is Expired');
            }
            else if(paymentIntent.Status__c == 'payment_done') {
                assert(false, 'Payment is Completed');
                paymentReceipt = new Stripe.Payments();
                // List<Payment> payment = new List<Payment>();
                paymentReceipt.registerPayment(paymentIntent);
                Transaction__c completedTxn = txnService.getTransactionPaymentIntentId(paymentIntent.Id);
                paymentReceipt.registerPayment(completedTxn);
                system.debug('paymentReceipt ' + paymentReceipt);
                system.debug('payments ' + payments);

            }
        }
        // TO DO Make it Dynamic
        // Integration Config
        stripePaymentGateway = [SELECT Id,Name,Gateway_Public_Key__c,Access_Token__c,Test_Mode__c,CreatedDate,LastModifiedDate,OwnerId FROM Payment_Gateway__c LIMIT 1];

        organization = stripePaymentGateway.Name;
        stripePublishableKey = stripePaymentGateway.Gateway_Public_Key__c;
        appMode = stripePaymentGateway.Test_Mode__c;
        assert(organization != null, System.Label.error_message_invalid_organization);
        assert(stripePublishableKey != null, System.Label.error_message_stripe_setup_error);
		
        //Custom Labels Collection
        labels = customLabelsService.getCustomLabels();
        labelsJson = JSON.serialize(labels);

    }
    public void assert(Boolean condition, String message) {
        if (!condition) {
            this.error = message;
        }
    }


    public void initCards() {
        if(!paymentRequests.isEmpty()){
            Stripe.PaymentMethods paymentMethods = stripeService.getPaymentMethods(contact.Id);
            cards = paymentMethods.cards;
        }
    }

    public void charge() {
        error = null;
        System.debug('User payment request : ' + stripePaymentRequestJson);
        Stripe.UserPaymentRequest stripePaymentRequest = new Stripe.UserPaymentRequest();
        try {
            stripePaymentRequest = (Stripe.UserPaymentRequest) JSON.deserialize(stripePaymentRequestJson, Stripe.UserPaymentRequest.class);
            System.debug('test paymentRequests Request'+ paymentRequests);
            System.debug('test StripePayment Request'+ stripePaymentRequest);
            payments = stripeService.processPayments(paymentRequests, stripePaymentRequest);
            System.debug('Bulk payment response : ' + JSON.serialize(payments));
            /*
            for(Stripe.Payments payment: payments){
                System.debug('test payment response : ' + payment);
                //Transaction__c txnDetails = txnService.getTransactionByChargeId(payment.txn.StripeChargeId__c);
                //payment.txn = txnDetails;
            }
            */

        } catch (JSONException ex) {
            error = System.Label.error_message_bad_request;
        }
        error = null;
    }
}