force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>PMA Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMA Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PMA Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>PMA Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMA Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PMA Products</relationshipLabel>
    <relationshipName>PMA_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PMA Products</relationshipLabel>
    <relationshipName>PMA_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Display_URL__c.field-meta.xml
<CustomField>
    <fullName>Display_URL__c</fullName>
    <label>Display URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Membership Fees</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
                <default>true</default>
                <label>POS</label>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU__c</fullName>
    <label>Product SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Quantity_Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Unit_Of_Measure__c</fullName>
    <label>Quantity Unit Of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Each</fullName>
                <default>true</default>
                <label>Each</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PMA_ProductsController.cls
public with sharing class PMA_ProductsController {
    //To create Order Item records
    @AuraEnabled
    public static Order__c createOrderItems(Id orderId, String selectedProductsValues) {
        Order__c checkOrderStatus = PMA_SearchController.getOrderDetailsByIdOrUUID( orderId );
       System.debug('checkOrderStatus  ' + checkOrderStatus);
       if(checkOrderStatus.Status__c == 'Draft'){
           checkOrderStatus.Status__c = 'Active';
           update checkOrderStatus;
       }
        List<Order_Item__c> orderItemList = new List<Order_Item__c>();
        System.debug('selectedProductsValues ' + selectedProductsValues);
        List< SelectedProductWrapper> prodWrapperList = (List< SelectedProductWrapper>)JSON.deserialize(selectedProductsValues,List<SelectedProductWrapper>.class); //re is response body string
        for(SelectedProductWrapper selectedProduct : prodWrapperList){
            Order_Item__c orderItemNew = new Order_Item__c();
            orderItemNew.Order__c = orderId;
            orderItemNew.Product__c = selectedProduct.product.Id;
            orderItemNew.Quantity__c = selectedProduct.quantity;
            orderItemList.add(orderItemNew);
        }
       System.debug('orderItemList  ' + orderItemList);
       insert orderItemList;

       Order__c currentOrder = PMA_SearchController.getOrderDetailsByIdOrUUID( orderId );
       System.debug('currentOrder  ' + currentOrder);
       return currentOrder;
    }
    //To return initial records
    @AuraEnabled
    public static Map <Id, SelectedProductWrapper > getAllProductRecords() {
        List < Product__c > productsList = new List < Product__c >();
        Map <Id, SelectedProductWrapper > mapProductsList = new Map <Id, SelectedProductWrapper >();
        try {
            //TODO  - change query from PBE instead of product
           // productsList = Database.query('SELECT '+ SYS_Helper.getAllFieldsFor('Product__c') + '\')');
           
            productsList = [SELECT Id,Name,Unit_Price__c,Account__c,Account__r.Name,Active__c,Contact__c,Display_URL__c,External_ID__c,Product_Code__c,Product_Description__c,Product_Family__c,Product_SKU__c,Quantity_Unit_Of_Measure__c,SystemModstamp,OwnerId,CreatedById,CreatedDate,IsDeleted,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate FROM Product__c WHERE Product_Family__c = 'POS' ORDER BY Name ASC];
            //productsList = [SELECT Id, Name, Unit_Price__c, Account__c, ProductCode, Description, IsActive, DisplayUrl, Family, QuantityUnitOfMeasure, StockKeepingUnit, ExternalDataSourceId, ExternalId FROM Product2 ORDER BY Name ASC];
           
            for( Product__c prod: productsList){
                String recordPictureURL = ImageController.getSysTrackRecordPictureURL(prod.Id);
                System.debug('Prod Name ' + prod.Name + ' recordPictureURL '+ recordPictureURL);
                SelectedProductWrapper selectedproduct = new SelectedProductWrapper();
                selectedproduct.product=prod;
                selectedproduct.quantity=1;
                selectedproduct.pictureURL=recordPictureURL;
                mapProductsList.put(prod.Id, selectedproduct);
            }
        } catch (Exception e) {
            //TODO add  to wrapper to pmaexception wrapper(class,method ,exception) and insert into log
            System.debug('Got Exception: ' + e.getMessage());
        }
        return mapProductsList;
    }
    @AuraEnabled
    public static Order__c getOrderDetails( String orderIdOrUUID ){
        Order__c currentOrder = PMA_SearchController.getOrderDetailsByIdOrUUID( orderIdOrUUID );
        return currentOrder;
    }
    // wrapper class selectedProduct.PricebookEntries[0].UnitPrice
    public class SelectedProductWrapper {
        @AuraEnabled
        public Integer quantity = 0;
        @AuraEnabled
        public Product__c product = new Product__c ();
        @AuraEnabled
        public Double productPrice{
            get { return (product != null) ? product.Unit_Price__c : 0; }
        }
        @AuraEnabled
        public Double totalProductPrice{
            get { return (productPrice != null) ? productPrice * quantity : 0; }
        }
        @AuraEnabled
        public String pictureURL;
    }
}