force-app/main/default/objects/FieldSetting__mdt/FieldSetting__mdt.object-meta.xml
<CustomObject>
    <label>Field Setting</label>
    <pluralLabel>Field Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FieldSetting__mdt/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TWOWAY</fullName>
                <default>true</default>
                <label>TWOWAY</label>
            </value>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>NOMERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieldSetting__mdt/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <description>Same as one used in SOQL. Supports parent fields</description>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldSetting__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieldSetting__mdt/fields/Is_External_Field__c.field-meta.xml
<CustomField>
    <fullName>Is_External_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>It is used to create a map of External Key by resource and is relevant for inbound only</inlineHelpText>
    <label>Is External Field?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieldSetting__mdt/fields/Is_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Is_Lookup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Lookup?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieldSetting__mdt/fields/ObjectSetting__c.field-meta.xml
<CustomField>
    <fullName>ObjectSetting__c</fullName>
    <label>Object Setting</label>
    <referenceTo>ObjectSetting__mdt</referenceTo>
    <relationshipName>DataMappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/IntegrationEnablement__mdt/IntegrationEnablement__mdt.object-meta.xml
<CustomObject>
    <label>Integration Enablement</label>
    <pluralLabel>Integration Enablement</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationEnablement__mdt/fields/Enable__c.field-meta.xml
<CustomField>
    <fullName>Enable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IntegrationEnablement__mdt/fields/Integration_Setting__c.field-meta.xml
<CustomField>
    <fullName>Integration_Setting__c</fullName>
    <label>Integration Setting</label>
    <referenceTo>IntegrationSetting__mdt</referenceTo>
    <relationshipLabel>Integration Enablement</relationshipLabel>
    <relationshipName>Integration_Enablement</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/IntegrationSetting__mdt.object-meta.xml
<CustomObject>
    <label>Integration Setting</label>
    <pluralLabel>Integration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationSetting__mdt/fields/EscapeCharacter__c.field-meta.xml
<CustomField>
    <fullName>EscapeCharacter__c</fullName>
    <label>Escape Character</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/fields/Notification_Wrapper__c.field-meta.xml
<CustomField>
    <fullName>Notification_Wrapper__c</fullName>
    <label>Notification Wrapper</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/fields/Notifications_are_partial__c.field-meta.xml
<CustomField>
    <fullName>Notifications_are_partial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notifications are partial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ObjectSetting__mdt/ObjectSetting__mdt.object-meta.xml
<CustomObject>
    <label>Object Setting</label>
    <pluralLabel>Object Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/municonhealthcheckcontroller.cls
public class municonhealthcheckcontroller {
    @AuraEnabled
    public  static boolean Escapcharectercheck() {
        Boolean Escapcharecter ;
        list<IntegrationSetting__mdt> integrationlist = [Select Id,Label  from IntegrationSetting__mdt WHERE developerName = 'Quickbooks'And EscapeCharacter__c !=null];
        system.debug('integrationlist+++'+integrationlist);
        
        if(integrationlist.size()!= Null && integrationlist.size()!= 0){
            Escapcharecter = true;
            system.debug('Escapcharecter=='+Escapcharecter);
            
        } else {
            Escapcharecter = false;  
            system.debug('Escapcharecter=='+Escapcharecter);
        }
        
        return Escapcharecter ;
    }
    
    
    @AuraEnabled   
    public  static Boolean isExternalcheck() {
        Boolean isexternalcheck;
        try{
            List <FieldSetting__mdt> AllFieldSettingsList = new List <FieldSetting__mdt>();
            AllFieldSettingsList = [Select id,FieldApiName__c from FieldSetting__mdt WHERE Is_Active__c=true 
                                    AND ObjectSetting__r.developerName = 'AccountQB' AND Is_External_Field__c = true];
            system.debug('AllFieldSettingsList++++=='+AllFieldSettingsList);
            if(AllFieldSettingsList.size()!=null && AllFieldSettingsList.size()!=0 ){
                
                isexternalcheck = true ;
                system.debug('isexternalcheckif'+isexternalcheck);
                
            }else{
                
                isexternalcheck = false;
                
                system.debug('isexternalcheck'+isexternalcheck);
                
            }
        } catch(Exception e) {
            System.debug('An exception occurred: ' + e.getMessage());
        }
        
        return isexternalcheck;
        
        //List<FieldSetting__mdt> ls1 = new List<FieldSetting__mdt>();
        
        
        
    }
    @AuraEnabled
    public  static Boolean intEnablement() {
        Boolean enablemenInteg;
        list<IntegrationEnablement__mdt> enablemenIntegList = [Select MasterLabel from IntegrationEnablement__mdt WHERE Integration_Setting__r.developerName ='Quickbooks' AND Enable__c = true];
        System.debug('enablemenIntegList+++=='+enablemenIntegList);
        if(enablemenIntegList.size()!= Null && enablemenIntegList.size()!= 0){
            enablemenInteg = true;
            system.debug('enablemenInteg=='+enablemenInteg);
        } else {
            enablemenInteg = false;  
            system.debug('enablemenInteg=='+enablemenInteg);
        }
        return enablemenInteg;
        
    }
    @AuraEnabled
    public  static Boolean Notificationpartialcheck() {
        Boolean Notificationpartial ;
        list<IntegrationSetting__mdt> NotificationIntList = [Select Id,Label  from IntegrationSetting__mdt WHERE developerName = 'Quickbooks'AND Notifications_are_partial__c = true AND Notification_Wrapper__c =null ];
        system.debug('NotificationIntList+++=='+NotificationIntList);
        if(NotificationIntList.size()== 0){
            Notificationpartial = true;
            system.debug('NotificationpartialIF'+Notificationpartial);
        } else {
            Notificationpartial = false;  
            system.debug('NotificationpartialElse=='+Notificationpartial);
        }
        return Notificationpartial;
    }
    @AuraEnabled
    public  static Boolean fieldsettingLookupTowayCheck() {
         Boolean fieldsettingLookup;
        list<FieldSetting__mdt> fieldsettinglookupList = [Select id from FieldSetting__mdt WHERE Is_Lookup__c = true AND Direction__c = 'TWOWAY' ];
        system.debug('fieldsettinglookup++'+fieldsettinglookupList);
       if( fieldsettinglookupList.size()== 0){
            fieldsettingLookup = true;
            system.debug('fieldsettingLookup=='+fieldsettingLookup);
            
        } else {
            fieldsettingLookup = false;  
            system.debug('fieldsettingLookup=='+fieldsettingLookup);
        }
        
        return fieldsettingLookup ;
    }
    
    
}