force-app/main/default/objects/FieldSetting__mdt/FieldSetting__mdt.object-meta.xml
<CustomObject>
    <label>Field Setting</label>
    <pluralLabel>Field Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FieldSetting__mdt/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <description>Same as one used in SOQL. Supports parent fields</description>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Callout_URL__c.field-meta.xml
<CustomField>
    <fullName>Callout_URL__c</fullName>
    <label>Callout URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Custom_Apex_Handler__c.field-meta.xml
<CustomField>
    <fullName>Custom_Apex_Handler__c</fullName>
    <label>Custom Apex Handler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data1__c.field-meta.xml
<CustomField>
    <fullName>data1__c</fullName>
    <label>data1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/How_to_process__c.field-meta.xml
<CustomField>
    <fullName>How_to_process__c</fullName>
    <label>How to process?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>use_object_setting</fullName>
                <default>true</default>
                <label>Use Object Setting</label>
            </value>
            <value>
                <fullName>use_custom_apex_handler</fullName>
                <label>Use Custom Apex Handler</label>
            </value>
            <value>
                <fullName>ignore_log</fullName>
                <label>Ignore Log</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Integration_Setting__c.field-meta.xml
<CustomField>
    <fullName>Integration_Setting__c</fullName>
    <label>Integration Setting</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/ObjectSettingId__c.field-meta.xml
<CustomField>
    <fullName>ObjectSettingId__c</fullName>
    <label>Object Setting</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Request_Digest__c.field-meta.xml
<CustomField>
    <fullName>Request_Digest__c</fullName>
    <label>Request Digest</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/retry__c.field-meta.xml
<CustomField>
    <fullName>retry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;NEW&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>CALLOUT ERROR</label>
            </value>
            <value>
                <fullName>PENDING_PARENT</fullName>
                <label>PENDING PARENT</label>
            </value>
            <value>
                <fullName>READY_FOR_PROCESSING</fullName>
                <label>READY FOR PROCESSING</label>
            </value>
            <value>
                <fullName>ENQUEUED_FOR_RETRY</fullName>
                <label>ENQUEUED FOR RETRY</label>
            </value>
            <value>
                <fullName>READY_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>READY_FOR_PARENT</label>
            </value>
            <value>
                <fullName>WAITING_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>WAITING_FOR_PARENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_Http_Status__c.field-meta.xml
<CustomField>
    <fullName>SYS_Http_Status__c</fullName>
    <label>Http Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>SYS_Operation_Type__c</fullName>
    <label>Operation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MERGE</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>UPSERT</fullName>
            </value>
            <value>
                <fullName>INSERT</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
            <value>
                <fullName>CDC</fullName>
                <isActive>false</isActive>
                <label>CDC</label>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
                <isActive>false</isActive>
                <label>RESPONSE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_RequestId__c.field-meta.xml
<CustomField>
    <fullName>SYS_RequestId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RequestId</label>
    <referenceTo>SYS_IntegrationLog__c</referenceTo>
    <relationshipLabel>Callout Response Logs</relationshipLabel>
    <relationshipName>RequestId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_OAuthConfig__c/SYS_OAuthConfig__c.object-meta.xml
<CustomObject>
    <label>SYS_OAuthConfig</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SYS_OAuthConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_OAuthConfig__c/fields/Object_Setting__c.field-meta.xml
<CustomField>
    <fullName>Object_Setting__c</fullName>
    <inlineHelpText>DeveloperName of the Object Setting to be used for this record to be processed</inlineHelpText>
    <label>Object Setting</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_OAuthConfig__c/fields/Token_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Token_Endpoint__c</fullName>
    <label>Token Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SYS_OAuthRedirectHandler.cls
@RestResource(urlMapping='/v1/callback/*')
global without sharing class SYS_OAuthRedirectHandler extends SYS_ApplicationService{

    private static String authCode;
    private static String calloutUrl;

    global override String getHttpRequestEndpoint(HttpRequest req,SYS_IntegrationLog__c log, String externalId){
        if(SYS_DataCache.INT_TYPE !=NULL && SYS_DataCache.OBJ_TYPE !=NULL){
            String baseEndpoint = SYS_DataCache.integrationSetting.get(SYS_Datacache.INT_TYPE).BaseAPIEndPoint__c;
            String resourceUrl = baseEndpoint + SYS_DataCache.objectSettingMap.get(SYS_DataCache.OBJ_TYPE).ResourcePath__c;
            
            String urlParams='';
            if(SYS_DataCache.objectSettingMap.get(SYS_DataCache.OBJ_TYPE).url_params__c != NULL)
                        urlParams = SYS_DataCache.objectSettingMap.get(SYS_DataCache.OBJ_TYPE).url_params__c;
                
            if(urlParams!=''){
                resourceUrl+='/'+urlParams;
            }
            

            log.Callout_URL__c = resourceUrl;
            
            return resourceUrl;
        }else{
            return super.getHttpRequestEndpoint(req, log, externalId);
        }
    }


    global override sObject processFieldMapping(FieldSetting__mdt mapping,sObject sObj,Object value, String sObjectApiName){
        sObj.put(mapping.FieldApiName__c,SYS_Helper.secondsToDatetime(String.valueOf(value)));
        return sObj;
    }

    global override String preprocessJSONForOutbound(SYS_IntegrationLog__c log,String jsonBody,HttpRequest req) {
        
        String formUrlEncodedBody='';
        Map<String,Object> jsonobj = SYS_Helper.getFlatKeys(jsonBody, 'A[B]');//(Map<String,Object>)JSON.deserializeUntyped(flatJSON);
        List<String> reqkeymap = new List<String>(jsonobj.keySet());
        List<String> keyValueList = new List<String>();
        reqkeymap.sort();

        for (String key: reqkeymap) {
            if (!String.isBlank(key)){
                keyValueList.add(key.toLowerCase() + '=' + EncodingUtil.urlEncode(String.valueOf(jsonobj.get(key)!=NULL?jsonobj.get(key):''),'UTF-8'));
            }
        }
        if(authCode!=NULL)
        keyValueList.add('code' + '=' + EncodingUtil.urlEncode(authCode,'UTF-8'));

        formUrlEncodedBody = String.join(keyValueList,'&');
        log.data1__c = formUrlEncodedBody; 

        jsonBody = formUrlEncodedBody;
        
        return jsonBody;
    }

    /* public override SYS_IntegrationLog__c generatelogForOutboundResult(HttpResponse resp,SYS_IntegrationLog__c log){

        SYS_IntegrationLog__c logResp = SYS_Helper.getLogsToInsert(resp.getBody());

        String algo = SYS_DataCache.integrationSetting.get(SYS_DataCache.INT_TYPE).Hashing_Algo__c;
        if(algo!=NULL && algo!='')
            logResp.Request_Digest__c = generateHash(resp.getBody(),algo);

        if(resp.getStatusCode() != 201 && resp.getStatusCode() != 200){

            log.Status__c = 'FAIL';

            logResp.Status__c = 'ERROR';
            
            logresp.SYS_Http_Status__c = Integer.valueOf(resp.getStatusCode());
            logResp.WhatId__c = log.WhatId__c;
            logResp.Type__c = SYS_Constants.RESPONSE;
            logResp.How_To_Process__c = 'ignore_log';
            logResp.Integration_Setting__c = SYS_DataCache.INT_TYPE;
            
        }
        else{
            log.Status__c = 'DONE';

            logResp.Status__c = SYS_Constants.NEW_STATUS;
            logResp.SYS_Operation_Type__c = 'UPDATE';

            logResp.Resource__c = SYS_DataCache.objectSettingMap.get(SYS_DataCache.OBJ_TYPE).Resource_Name__c;
            logResp.How_To_Process__c = 'use_custom_apex_handler';
            logResp.Custom_Apex_Handler__c = SYS_DataCache.integrationSetting.get(SYS_DataCache.INT_TYPE).ApexHandler__c;
            
            logresp.SYS_Http_Status__c = Integer.valueOf(resp.getStatusCode());
            logResp.WhatId__c = log.WhatId__c;
            logResp.Type__c = SYS_Constants.RESPONSE;
            logResp.Integration_Setting__c = SYS_DataCache.INT_TYPE;
            logResp.ObjectSettingId__c = log.ObjectSettingId__c;

            logResp.retry__c = false; 
            
        }

        SYS_Helper.upsertLog(log);
        logResp.SYS_RequestId__c = log.Id;

        return logResp;
    } */

	@HttpGet
    global static void doGet(){
        if(RestContext.response!=NULL){
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.addHeader('Access-Control-Allow-Origin', '*');
        }
        String code= RestContext.request.params.get('code');
        String state = RestContext.request.params.get('state');
        
        authCode = code;
        
        String query = 'SELECT '+SYS_Helper.getAllFieldsFor('SYS_OAuthConfig__c')+' FROM SYS_OAuthConfig__c';
        String whereClause = ' WHERE Id =\''+String.escapeSingleQuotes(state)+'\'';
        List<SYS_OAuthConfig__c> configs = Database.query(String.escapeSingleQuotes(query)+whereClause);
        
        if(configs.size()>0){
            calloutUrl = configs[0].Token_Endpoint__c;
            try{

                SYS_DataCache.OBJ_TYPE = configs[0].Object_Setting__c;
                SYS_DataCache.INT_TYPE = SYS_DataCache.objectSettingMap.get(configs[0].Object_Setting__c).IntegrationType__r.DeveloperName;
                SYS_IntegrationLog__c  newSysLog = new SYS_IntegrationLog__c();
                List<SYS_IntegrationLog__c> insertSysLog = new List<SYS_IntegrationLog__c>();
                
                SYS_ApplicationService appService = (SYS_ApplicationService)Type.forName(SYS_DataCache.objectSettingMap.get(SYS_DataCache.OBJ_TYPE).ApexHandler__c).newInstance();
                Map<Id, String> jsonListForOutbound = appService.transformSObjectToJson(configs);
                
                if(jsonListForOutbound.values().size() > 0){
                    for(Id jsonRecordId:jsonListForOutbound.keyset()){ 
                        String finalJsonForOutbound;

                        finalJsonForOutbound = appService.sanitizeJSONForOutbound(jsonListForOutbound.get(jsonRecordId));

                        newSysLog = SYS_Helper.getLogsToInsert(finalJsonForOutbound);
                        newSysLog.Status__c = SYS_Constants.NEW_STATUS;
                        newSysLog.HTTP_Method__c = 'POST';
                        newSysLog.Type__c = SYS_Constants.OUTBOUND;
                        newSysLog.Integration_Setting__c = SYS_DataCache.INT_TYPE;
                        newSysLog.How_to_process__c = 'use_object_setting';
                        newSysLog.ObjectSettingId__c = SYS_DataCache.OBJ_TYPE;
                        newSysLog.SYS_Operation_Type__c = 'INSERT';
                        //newSysLog.Callout_URL__c = configs[0].Token_Endpoint__c;
                        newSysLog.Custom_Field_Value__c = code;
                        newSysLog.WhatId__c = state;
                        
                        newSysLog.retry__c = false;
                        insertSysLog.add(newSysLog);
                    }

                    if(insertSysLog.size()>0 && SYS_DataCache.enableCheck.get(SYS_DataCache.INT_TYPE.toUpperCase())){
                        new SYS_IntegrationLogOutboundImmediate(insertSysLog).execute();
                    }
                    if(RestContext.response!=null)
                    RestContext.response.responseBody = 
                    Blob.valueOf('Token Generated succesfully.');
                    
                }
            }catch(Exception e){
                if(RestContext.response!=null)
                RestContext.response.responseBody = 
                    Blob.valueOf('Something went wrong while trying to call token url \n'+e.getMessage() + '\n' +e.getStackTraceString());
            }
            

        }else{
            RestContext.response.responseBody = Blob.valueOf('{"error":'+'Invalid Config Id. Authentication Failed'+'}');
        }
        
    }
}