force-app/main/default/objects/FieldSetting__mdt/FieldSetting__mdt.object-meta.xml
<CustomObject>
    <label>Field Setting</label>
    <pluralLabel>Field Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FieldSetting__mdt/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <description>Same as one used in SOQL. Supports parent fields</description>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldSetting__mdt/fields/Get_value_from_Log__c.field-meta.xml
<CustomField>
    <fullName>Get_value_from_Log__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this checkbox is checked then the value for the field corresponding to this field setting will be derived from the field referred by the API name in Log API for field mapping</description>
    <inlineHelpText>If this checkbox is checked then the value for the field corresponding to this field setting will be derived from the field referred by the API name in Log API for field mapping</inlineHelpText>
    <label>Get value from Log</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieldSetting__mdt/fields/Is_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Is_Lookup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Lookup?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieldSetting__mdt/fields/Log_API_for_field_mapping__c.field-meta.xml
<CustomField>
    <fullName>Log_API_for_field_mapping__c</fullName>
    <inlineHelpText>Enter the API Name of the field on SYS Log that should be used for setting the value to this field setting. This applies only when the Get Value from log is checked</inlineHelpText>
    <label>Log API for field mapping</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldSetting__mdt/fields/Lookup_External_Key__c.field-meta.xml
<CustomField>
    <fullName>Lookup_External_Key__c</fullName>
    <inlineHelpText>The External Id field of the Lookup object</inlineHelpText>
    <label>Lookup External Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldSetting__mdt/fields/Lookup_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Object_API_Name__c</fullName>
    <label>Lookup Object (API Name)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldSetting__mdt/fields/StaticValue__c.field-meta.xml
<CustomField>
    <fullName>StaticValue__c</fullName>
    <label>Static Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Custom_Apex_Handler__c.field-meta.xml
<CustomField>
    <fullName>Custom_Apex_Handler__c</fullName>
    <label>Custom Apex Handler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/External_Id_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Id_Field_API_Name__c</fullName>
    <description>This field is populated from webservice for Inbound only</description>
    <label>External Id Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Flat_Key_for_Resource__c.field-meta.xml
<CustomField>
    <fullName>Flat_Key_for_Resource__c</fullName>
    <description>Defines the flat key in incoming JSON that will be used to identify the Resource and hence the object setting</description>
    <label>Flat Key for Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/How_to_process__c.field-meta.xml
<CustomField>
    <fullName>How_to_process__c</fullName>
    <label>How to process?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>use_object_setting</fullName>
                <default>true</default>
                <label>Use Object Setting</label>
            </value>
            <value>
                <fullName>use_custom_apex_handler</fullName>
                <label>Use Custom Apex Handler</label>
            </value>
            <value>
                <fullName>ignore_log</fullName>
                <label>Ignore Log</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Request_Digest__c.field-meta.xml
<CustomField>
    <fullName>Request_Digest__c</fullName>
    <label>Request Digest</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;NEW&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>CALLOUT ERROR</label>
            </value>
            <value>
                <fullName>PENDING_PARENT</fullName>
                <label>PENDING PARENT</label>
            </value>
            <value>
                <fullName>READY_FOR_PROCESSING</fullName>
                <label>READY FOR PROCESSING</label>
            </value>
            <value>
                <fullName>ENQUEUED_FOR_RETRY</fullName>
                <label>ENQUEUED FOR RETRY</label>
            </value>
            <value>
                <fullName>READY_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>READY_FOR_PARENT</label>
            </value>
            <value>
                <fullName>WAITING_FOR_PARENT</fullName>
                <isActive>false</isActive>
                <label>WAITING_FOR_PARENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_IntegrationSettings__c.field-meta.xml
<CustomField>
    <fullName>SYS_IntegrationSettings__c</fullName>
    <label>SYS_IntegrationSettings</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quickbooks</fullName>
            </value>
            <value>
                <fullName>JIRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>SYS_Operation_Type__c</fullName>
    <label>Operation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MERGE</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>UPSERT</fullName>
            </value>
            <value>
                <fullName>INSERT</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
            <value>
                <fullName>CDC</fullName>
                <isActive>false</isActive>
                <label>CDC</label>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
                <isActive>false</isActive>
                <label>RESPONSE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Drchrono_ApplicationService.cls
public class Drchrono_ApplicationService extends SYS_ApplicationService {
    Public static final map < string, string > mapEvent = new map < string, string > {
        'PATIENT_CREATE' => '/api/patients',
        'PATIENT_ALLERGY_CREATE' => '/api/allergies',
        'PATIENT_MEDICATION_CREATE' => '/api/medications',
        'PATIENT_PROBLEM_CREATE' => '/api/problems',
         'PATIENT_ALLERGY_MODIFY'=>'/api/allergies',
          'PATIENT_MODIFY' => '/api/patients',
        'PATIENT_MEDICATION_MODIFY' => '/api/medications',
        'PATIENT_PROBLEM_MODIFY' => '/api/problems'
    };
   

    public override SYS_IntegrationLog__c generateLogForWebhookReq(String method) {
        String requestBody = RestContext.request.requestBody.toString();
        String headerName = RestContext.request.headers.get('X-drchrono-event');
        system.debug('headerName--' + headerName);
        //JSON Without any Chunking to subJOSN
      
        Map < String, Object > jsonResp = (Map < String, Object > ) JSON.deserializeUntyped(requestBody);
        String JsonrequestBody = JSON.serialize(jsonResp.get('object'));
        SYS_IntegrationLog__c log = SYS_Helper.getLogsToInsert(JsonrequestBody);
        String algo = SYS_DataCache.integrationSetting.get(SYS_DataCache.INT_TYPE).Hashing_Algo__c;
        system.debug('JsonrequestBody--' + JsonrequestBody);
        system.debug('int1');
        if (algo != NULL && algo != '')
            log.Request_Digest__c = generateHash(requestBody, algo);
        log.Type__c = 'INBOUND';
        log.SYS_Operation_Type__c = getOperationTypeFor(method);
        log.Flat_Key_for_Resource__c = 'attributes.type';
        log.SYS_IntegrationSettings__c = SYS_DataCache.INT_TYPE;
        log.Status__c = 'NEW';
        //log.External_Id_Field_API_Name__c = 'SYS_Key__c';
        log.How_to_process__c = 'use_custom_apex_handler';
        log.Custom_Apex_Handler__c = 'Drchrono_ApplicationService';

        log.Resource__c = mapEvent.get(headerName);
        system.debug('Resource__c--' + log.Resource__c);
        return log;
    }
  
    public override void doGet() {
        String message = RestContext.request.params.get('msg');
        System.debug('message : ' + message);
        String token = SYS_DataCache.integrationSetting.get(SYS_DataCache.INT_TYPE).webhookToken__c;
        Blob key = Blob.valueOf(token);

        String secret_token = encodingUtil.convertToHex(Crypto.generateMac('hmacSHA256', Blob.valueof(message), key));

        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('secret_token', secret_token);
        gen.writeEndObject();
        system.debug('secret_token--' + gen.getAsString());
        RestContext.response.responseBody = Blob.valueOf(gen.getAsString());
        RestContext.response.statuscode = 200;
    }
    public override sObject processFieldMapping(FieldSetting__mdt mapping, sObject sObj, Object value, String sObjectApiName) {

        System.debug(mapping.FieldApiName__c + ' +MS+ ' + value);
        if (mapping.Get_value_from_Log__c)
            value = SYS_DataCache.log.get(mapping.Log_API_for_field_mapping__c);

        if (mapping.Is_Lookup__c && mapping.Lookup_External_Key__c != NULL && mapping.Lookup_Object_API_Name__c != NULL) {
            value = getIdFromExternalKey(mapping.Lookup_Object_API_Name__c, mapping.Lookup_External_Key__c, String.valueOf(value));
        }

        if (mapping.StaticValue__c != NULL)
            value = mapping.StaticValue__c;


        if (value == NULL) return sObj;


        SObjectType r = ((SObject)(Type.forName('Schema.' + sObjectApiName).newInstance())).getSObjectType();
        DescribeSObjectResult d = r.getDescribe();

        String fieldType = d.fields
            .getMap()
            .get(mapping.FieldApiName__c)
            .getDescribe()
            .getType() + '';


        //TODO add other field types
        if (mapping.FieldApiName__c == 'External_Id__c' && value != null) {
            system.debug('Test Record create');
            sObj.put(mapping.FieldApiName__c, String.valueof(value));
        } else if (fieldType == 'DATE') {
            sObj.put(mapping.FieldApiName__c, date.valueOf((String) value));
        } else if (fieldType == 'STRING') {
            sObj.put(mapping.FieldApiName__c, String.valueof(value));
        } else if (fieldType == 'BOOLEAN') {
            sObj.put(mapping.FieldApiName__c, Boolean.valueof(value));
        } else {
            sObj.put(mapping.FieldApiName__c, value);
        }

        SYS_debug.log('MS FINAL SOBJ:' + sObj);
        return sObj;
    }
}